import {env} from 'cloudflare:workers';
import {cookies} from 'next/headers';
import {db,readState,saveState,bootstrapIdentity} from './server';
import {getChatGPTUser} from '../chatgpt-auth';
import {digest,token,hashPassword,verifyPassword,checkPasswordPolicy} from './passwords';
import type {Member} from './model';
export const COOKIE='__Host-dns-session';
export type Credential={user_id:string;password_hash:string;must_change:number;version:number;temp_expires:number|null;changed_at:number};
export const credentialFor=(id:string)=>db().prepare('SELECT * FROM credentials WHERE user_id=?').bind(id).first<Credential>();
export function cookie(value:string,maxAge=43200){return `${COOKIE}=${value}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=${maxAge}`;}
export async function getSession(){const raw=(await cookies()).get(COOKIE)?.value;if(!raw||!/^[a-f0-9]{64}$/.test(raw))return null;const hash=digest(raw);const row=await db().prepare('SELECT * FROM sessions WHERE token_hash=? AND expires>? AND last_seen>?').bind(hash,Date.now(),Date.now()-1800000).first<{user_id:string;credential_version:number}>();if(!row)return null;const credential=await credentialFor(row.user_id);if(!credential||credential.version!==row.credential_version||credential.must_change&&credential.temp_expires!==null&&credential.temp_expires<Date.now())return null;const state=await readState();const member=state.members.find(m=>m.id===row.user_id&&m.active);if(!member||member.role==='employee')return null;await db().prepare('UPDATE sessions SET last_seen=? WHERE token_hash=?').bind(Date.now(),hash).run();return {state,member,credential,hash};}
export async function createSession(member:Member,c:Credential){const raw=token(),now=Date.now();await db().prepare('INSERT INTO sessions(token_hash,user_id,credential_version,expires,last_seen) VALUES(?,?,?,?,?)').bind(digest(raw),member.id,c.version,now+(c.must_change?900000:43200000),now).run();return raw;}
export async function rateLimit(key:string,limit:number){const now=Date.now();const row=await db().prepare('INSERT INTO auth_attempts(key,count,until) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN until<? THEN 1 ELSE count+1 END,until=CASE WHEN until<? THEN excluded.until ELSE until END RETURNING count,until').bind(key,now+900000,now,now).first<{count:number;until:number}>();if(row&&row.count>limit)throw new Error('Слишком много попыток. Попробуйте через 15 минут.');}
export async function login(email:string,password:string,ip:string){if(typeof email!=='string'||typeof password!=='string'||email.length>200||password.length>128||!password.length)throw new Error('Неверный email или PIN');const normalized=email.trim().toLowerCase();await rateLimit('ip:'+digest(ip),30);await rateLimit('account:'+digest(normalized),10);const s=await readState();const member=s.members.find(m=>m.email.toLowerCase()===normalized&&m.active&&m.role!=='employee');const credential=member?await credentialFor(member.id):null;

// Equal-cost password work also for unknown accounts.
const dummy='scrypt$16384$8$5$00000000000000000000000000000000$0000000000000000000000000000000000000000000000000000000000000000';const valid=verifyPassword(password,credential?.password_hash||dummy);if(!member||!credential||!valid)throw new Error('Неверный email или PIN');if(credential.must_change&&credential.temp_expires!==null&&credential.temp_expires<Date.now())throw new Error('Временный PIN истёк. Обратитесь к администратору.');await db().prepare('DELETE FROM auth_attempts WHERE key=?').bind('account:'+digest(normalized)).run();return {member,credential,raw:await createSession(member,credential)};}
export async function setupOwner(password:string){checkPasswordPolicy(password);const {s,m}=await bootstrapIdentity();if(m.email!=='maiklvas@gmail.com')throw new Error('Настройка доступна только владельцу');if(await credentialFor(m.id))throw new Error('PIN уже задан. Используйте вход по PIN.');const hash=hashPassword(password),now=Date.now();m.branches=[];s.version++;s.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),actor:m.name,action:'PIN владельца настроен',entityId:m.id,detail:'Первичная настройка'});const stmt=db().prepare('INSERT INTO credentials(user_id,password_hash,must_change,version,temp_expires,changed_at) SELECT ?,?,0,1,NULL,? WHERE EXISTS(SELECT 1 FROM app_state WHERE id=1 AND version=?)').bind(m.id,hash,now,s.version-1);await saveState(s,s.version-1,undefined,[stmt]);const c=(await credentialFor(m.id))!;return {member:m,credential:c,raw:await createSession(m,c)};}
export async function changePassword(current:string,next:string){const auth=await getSession();if(!auth)throw new Error('Войдите в аккаунт');await rateLimit('password:'+auth.member.id,10);checkPasswordPolicy(next);if(typeof current!=='string'||current.length>128||!verifyPassword(current,auth.credential.password_hash))throw new Error('Текущий PIN неверен');if(verifyPassword(next,auth.credential.password_hash))throw new Error('Новый PIN должен отличаться от текущего');const hash=hashPassword(next),now=Date.now();const s=auth.state;const effect=db().prepare('UPDATE credentials SET password_hash=?,must_change=0,version=version+1,temp_expires=NULL,changed_at=? WHERE user_id=? AND version=? AND EXISTS(SELECT 1 FROM app_state WHERE id=1 AND version=?)').bind(hash,now,auth.member.id,auth.credential.version,s.version);s.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),actor:auth.member.name,action:'PIN изменён',entityId:auth.member.id,detail:'Предыдущие сеансы завершены'});s.version++;await saveState(s,s.version-1,undefined,[effect]);const c=(await credentialFor(auth.member.id))!;return {member:auth.member,credential:c,raw:await createSession(auth.member,c)};}
export async function authStatus(){const a=await getSession();if(a)return {selfHosted:(env as any).SELF_HOSTED==='true',authenticated:true,mustChange:!!a.credential.must_change,user:{id:a.member.id,name:a.member.name,email:a.member.email,role:a.member.role,phone:a.member.phone||'',avatarVersion:a.member.avatarVersion||0},canSetupOwner:false};const owner=await getChatGPTUser();const s=await readState();const m=s.members.find(x=>x.email==='maiklvas@gmail.com');const canSetupOwner=owner?.email?.toLowerCase()==='maiklvas@gmail.com'&&(!m||!await credentialFor(m.id));const canRecoverOwner=owner?.email?.toLowerCase()==='maiklvas@gmail.com'&&(!m||m.active&&m.role==='admin');return {selfHosted:(env as any).SELF_HOSTED==='true',authenticated:false,canSetupOwner,canRecoverOwner,ownerEmail:canRecoverOwner?owner?.email:null};}
export async function logout(){const raw=(await cookies()).get(COOKIE)?.value;if(raw)await db().prepare('DELETE FROM sessions WHERE token_hash=?').bind(digest(raw)).run();}

export async function recoverOwner(password:string){const verified=await getChatGPTUser();if(verified?.email?.toLowerCase()!=='maiklvas@gmail.com')throw new Error('Подтвердите аккаунт владельца через ChatGPT');await rateLimit('owner-recovery',5);checkPasswordPolicy(password);const {s,m}=await bootstrapIdentity();if(m.email!=='maiklvas@gmail.com'||m.role!=='admin'||!m.active)throw new Error('Восстановление недоступно');const hash=hashPassword(password),now=Date.now(),old=s.version;const effect=db().prepare('INSERT INTO credentials(user_id,password_hash,must_change,version,temp_expires,changed_at) SELECT ?,?,0,1,NULL,? WHERE EXISTS(SELECT 1 FROM app_state WHERE id=1 AND version=?) ON CONFLICT(user_id) DO UPDATE SET password_hash=excluded.password_hash,must_change=0,version=credentials.version+1,temp_expires=NULL,changed_at=excluded.changed_at').bind(m.id,hash,now,old);const unlock=db().prepare('DELETE FROM auth_attempts WHERE key=? AND EXISTS(SELECT 1 FROM app_state WHERE id=1 AND version=?)').bind('account:'+digest(m.email),old);m.branches=[];s.audit.unshift({id:crypto.randomUUID(),at:new Date(now).toISOString(),actor:m.name,action:'PIN владельца восстановлен',entityId:m.id,detail:'Личность подтверждена через ChatGPT. Старые сеансы завершены.'});s.version++;await saveState(s,old,undefined,[effect,unlock]);const c=(await credentialFor(m.id))!;return {member:m,credential:c,raw:await createSession(m,c)};}
