// Monthly layout and native chart were authored with @oai/artifact-tool.
// This small runtime fills and clones that template without a spreadsheet engine in the Worker.
import template from './excel-template.json';
import {dateAdd,planHours,jobText,statusText,scoped,type State,type Member} from './model';
const enc=new TextEncoder();
const esc=(v:unknown)=>String(v??'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;');
const serial=(date:string)=>Date.parse(date+'T00:00:00Z')/86400000+25569;
const time=(value:string)=>{const [h,m]=value.split(':').map(Number);return (h*60+m)/1440;};
const round=(n:number)=>Math.round(n*100)/100;
export function validatePeriod(from:string,to:string){const valid=(s:string)=>/^20\d{2}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s;if(!valid(from)||!valid(to)||from>to)throw new Error('Укажите корректный период: начало не позже конца');}
export const fileName=(name:string,from:string,to:string)=>`${name.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[. ]+$/g,'').slice(0,140)||'Филиал'}_${from}_${to}.xlsx`;
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
const crc=(b:Uint8Array)=>{let c=0xffffffff;for(const v of b)c=crcTable[(c^v)&255]^(c>>>8);return (c^0xffffffff)>>>0;};
export function zip(files:Record<string,string|Uint8Array>){const local:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0,centralSize=0;
for(const [name,value] of Object.entries(files)){const path=enc.encode(name),body=typeof value==='string'?enc.encode(value):value,checksum=crc(body);const h=new Uint8Array(30+path.length),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(12,33,true);v.setUint32(14,checksum,true);v.setUint32(18,body.length,true);v.setUint32(22,body.length,true);v.setUint16(26,path.length,true);h.set(path,30);local.push(h,body);const c=new Uint8Array(46+path.length),d=new DataView(c.buffer);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x800,true);d.setUint16(14,33,true);d.setUint32(16,checksum,true);d.setUint32(20,body.length,true);d.setUint32(24,body.length,true);d.setUint16(28,path.length,true);d.setUint32(42,offset,true);c.set(path,46);central.push(c);centralSize+=c.length;offset+=h.length+body.length;}
if(offset+centralSize>96*1024*1024)throw new Error('Выгрузка больше 96 МБ. Выберите меньший период или один филиал.');const end=new Uint8Array(22),v=new DataView(end.buffer);v.setUint32(0,0x06054b50,true);v.setUint16(8,central.length,true);v.setUint16(10,central.length,true);v.setUint32(12,centralSize,true);v.setUint32(16,offset,true);const result=new Uint8Array(offset+centralSize+22);let i=0;for(const part of [...local,...central,end]){result.set(part,i);i+=part.length;}return result;}
function months(from:string,to:string){const result:string[]=[];for(let m=from.slice(0,7);m<=to.slice(0,7);){result.push(m);const [y,n]=m.split('-').map(Number);m=n===12?`${y+1}-01`:`${y}-${String(n+1).padStart(2,'0')}`;}return result;}
export function branchWorkbook(s:State,branch:string,from:string,to:string){validatePeriod(from,to);const b=s.branches.find(b=>b.id===branch);if(!b)throw new Error('Филиал не найден');const base=template.files as Record<string,string>;const styles=template.styles as Record<string,number>;const files:Record<string,string>={};for(const [key,xml] of Object.entries(base))if(!/worksheets|drawings|workbook.xml|Content_Types/.test(key))files[key]=xml;
let sheets='',rels='',types='';const ns='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
months(from,to).forEach((month,i)=>{const n=i+1;const all=s.shifts.filter(x=>x.branch===branch&&x.date>=from&&x.date<=to&&x.date.startsWith(month)).sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)||a.employee.localeCompare(b.employee)||a.id.localeCompare(b.id));if(all.length>1048530)throw new Error('В месяце превышен предел строк Excel');const rows=new Map<number,string[]>();
function cell(ref:string,value:unknown,formula?:string,styleRef=ref){const style=styles[styleRef]??1;let xml=`<x:c r="${ref}" s="${style}"`;if(value===null||value===undefined){xml+=' />';}else if(typeof value==='number'){xml+=`>${formula?`<x:f>${esc(formula)}</x:f>`:''}<x:v>${round(value*100000000)/100000000}</x:v></x:c>`;}else if(formula){xml+=` t="str"><x:f>${esc(formula)}</x:f><x:v>${esc(value)}</x:v></x:c>`;}else{xml+=` t="inlineStr"><x:is><x:t xml:space="preserve">${esc(value)}</x:t></x:is></x:c>`;}const row=Number(ref.replace(/\D/g,''));rows.set(row,[...(rows.get(row)||[]),xml]);}
// Preserve the template's title, headers, merges, column sizes and native drawing.
const fixed=base['xl/worksheets/sheet1.xml'].match(/<x:row\b[^>]*>[\s\S]*?<\/x:row>/g)||[];for(const xml of fixed){const row=Number(xml.match(/r="(\d+)"/)![1]);if([1,2,3,5,7,27,28,29,40,43].includes(row))rows.set(row,[xml.replace(/^<x:row[^>]*>|<\/x:row>$/g,'')]);}
rows.set(1,[]);cell('A1',`DNS · ${b.name}`);rows.set(3,[]);cell('A3',`${month} · выбранный период ${from} — ${to}`);
const end=Math.max(44,43+all.length),seenPlan=new Set<string>(),seenFact=new Set<string>();
all.forEach((x,j)=>{const r=44+j,e=s.employees.find(e=>e.id===x.employee),key=x.date+':'+x.employee;const countPlan=x.status!=='cancelled'&&!seenPlan.has(key)?1:0;const countFact=x.status==='confirmed'&&(x.actualHours||0)>0&&!seenFact.has(key)?1:0;if(x.status!=='cancelled')seenPlan.add(key);if(x.status==='confirmed'&&(x.actualHours||0)>0)seenFact.add(key);
const values=[serial(x.date),x.employeeName||e?.name||'Сотрудник',jobText[x.employeeJob||e?.job||'hall'],time(x.start),time(x.end),x.breakMinutes,x.status==='cancelled'?0:planHours(x),x.reportedHours??null,x.status==='confirmed'?x.actualHours??0:null,statusText[x.status],x.quality||'',x.reason||x.report||'',x.confirmedBy||'',countPlan,countFact,x.employee];
const formulas:Record<number,string>={6:`IF(J${r}="Отменена",0,ROUND((MOD(E${r}-D${r},1)*1440-F${r})/60,2))`,13:`IF(J${r}="Отменена",0,IF(COUNTIFS($A$44:A${r},A${r},$P$44:P${r},P${r},$J$44:J${r},"<>Отменена")=1,1,0))`,14:`IF(AND(J${r}="Подтверждена",I${r}>0),IF(COUNTIFS($A$44:A${r},A${r},$P$44:P${r},P${r},$J$44:J${r},"Подтверждена",$I$44:I${r},">0")=1,1,0),0)`};values.forEach((v,k)=>cell(`${String.fromCharCode(65+k)}${r}`,v,formulas[k],`${String.fromCharCode(65+k)}44`));});
const days:string[]=[];for(let d=month+'-01';d.startsWith(month);d=dateAdd(d,1))if(d>=from&&d<=to)days.push(d);const daily=days.map(d=>{const xs=all.filter(x=>x.date===d&&x.status!=='cancelled');return {date:d,plan:new Set(xs.map(x=>x.employee)).size,fact:new Set(xs.filter(x=>x.status==='confirmed'&&(x.actualHours||0)>0).map(x=>x.employee)).size,ph:round(xs.reduce((a,x)=>a+planHours(x),0)),fh:round(xs.filter(x=>x.status==='confirmed').reduce((a,x)=>a+(x.actualHours||0),0)),pending:xs.filter(x=>x.status!=='confirmed').length};});
daily.forEach((d,j)=>{const r=8+j;const sum=(col:string)=>`SUMIF($A$44:$A$${end},A${r},$${col}$44:$${col}$${end})`;cell('A'+r,serial(d.date),undefined,'A8');cell('B'+r,d.plan,sum('N'),'B8');cell('C'+r,d.fact,sum('O'),'C8');cell('D'+r,d.ph,sum('G'),'D8');cell('E'+r,d.fh,sum('I'),'E8');cell('F'+r,d.pending,`COUNTIFS($A$44:$A$${end},A${r},$J$44:$J$${end},"<>Подтверждена",$J$44:$J$${end},"<>Отменена")`,'F8');cell('G'+r,round(d.fh-d.ph),`E${r}-D${r}`,'G8');cell('H'+r,`${Number(d.date.slice(8))}.${Number(d.date.slice(5,7))}`,`DAY(A${r})&"."&MONTH(A${r})`,'H8');});
rows.set(40,[]);cell('A40','Итого');for(const [col,key] of [['D','ph'],['E','fh'],['F','pending']] as const)cell(col+'40',round(daily.reduce((n,d)=>n+d[key],0)),`SUM(${col}8:${col}${7+days.length})`);cell('G40',round(daily.reduce((n,d)=>n+d.fh-d.ph,0)),'E40-D40');
const sheetData=[...rows].sort((a,b)=>a[0]-b[0]).map(([r,c])=>`<x:row r="${r}" ht="${r===7||r===43?36:r>=44?32:22}" customHeight="1">${c.join('')}</x:row>`).join('');let sheet=base['xl/worksheets/sheet1.xml'].replace(/<x:sheetData>[\s\S]*?<\/x:sheetData>/,`<x:sheetData>${sheetData}</x:sheetData>`).replace(/<x:sheetView ([^>]*)\/>/, '<x:sheetView $1><x:pane ySplit="7" topLeftCell="A8" activePane="bottomLeft" state="frozen" /></x:sheetView>');sheet=sheet.replace('<x:mergeCells',`<x:autoFilter ref="A43:P${end}" /><x:mergeCells`);files[`xl/worksheets/sheet${n}.xml`]=sheet;
files[`xl/worksheets/_rels/sheet${n}.xml.rels`]=base['xl/worksheets/_rels/sheet1.xml.rels'].replaceAll('drawing1.xml',`drawing${n}.xml`);files[`xl/drawings/drawing${n}.xml`]=base['xl/drawings/drawing1.xml'];files[`xl/drawings/_rels/drawing${n}.xml.rels`]=base['xl/drawings/_rels/drawing1.xml.rels'].replaceAll('chart1.xml',`chart${n}.xml`);
const cache=(vals:(string|number)[])=>`<c:ptCount val="${vals.length}" />`+vals.map((v,k)=>`<c:pt idx="${k}"><c:v>${esc(v)}</c:v></c:pt>`).join('');let series=0;const chart=base['xl/drawings/charts/chart1.xml'].replaceAll('Месяц',month).replaceAll('$38',`$${7+days.length}`).replace(/<c:strCache>[\s\S]*?<\/c:strCache>/g,()=>`<c:strCache>${cache(days.map(d=>`${Number(d.slice(8))}.${Number(d.slice(5,7))}`))}</c:strCache>`).replace(/<c:numCache>[\s\S]*?<\/c:numCache>/g,()=>`<c:numCache><c:formatCode>0</c:formatCode>${cache(daily.map(d=>series===0?d.plan:d.fact))}${(series++,'')}</c:numCache>`);files[`xl/drawings/charts/chart${n}.xml`]=chart;
sheets+=`<x:sheet name="${month}" sheetId="${n}" r:id="month${n}" />`;rels+=`<Relationship Type="${ns}/worksheet" Target="/xl/worksheets/sheet${n}.xml" Id="month${n}" />`;for(const [path,type] of [[`worksheets/sheet${n}.xml`,'spreadsheetml.worksheet'],[`drawings/drawing${n}.xml`,'drawing'],[`drawings/charts/chart${n}.xml`,'drawingml.chart']])types+=`<Override PartName="/xl/${path}" ContentType="application/vnd.openxmlformats-officedocument.${type}+xml" />`;
});
files['xl/workbook.xml']=`<?xml version="1.0" encoding="UTF-8"?><x:workbook xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="${ns}"><x:sheets>${sheets}</x:sheets><x:calcPr calcId="191029" fullCalcOnLoad="1" /></x:workbook>`;files['xl/_rels/workbook.xml.rels']=base['xl/_rels/workbook.xml.rels'].replace(/<Relationship\b[^>]*Type="[^"]*\/worksheet"[^>]*\/>/g,'').replace('</Relationships>',rels+'</Relationships>');files['[Content_Types].xml']=base['[Content_Types].xml'].replace(/<Override\b[^>]*PartName="\/xl\/(?:worksheets|drawings)[^"]*"[^>]*\/>/g,'').replace('</Types>',types+'</Types>');return zip(files);}
export function exportStatistics(source:State,member:Member,branch:string,from:string,to:string){if(!member.active||member.role==='employee')throw new Error('Выгрузка доступна администратору и управляющему');validatePeriod(from,to);const s=scoped(source,member);const branches=s.branches.filter(b=>branch==='all'||b.id===branch);if(!branches.length)throw new Error('Нет доступа к филиалу');const files:Record<string,Uint8Array>={};for(const b of branches){let name=fileName(b.name,from,to);if(files[name])name=fileName(b.name+'_'+b.id,from,to);files[name]=branchWorkbook(s,b.id,from,to);}const names=Object.keys(files);return names.length===1?{bytes:files[names[0]],name:names[0],type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}:{bytes:zip(files),name:`Филиалы_${from}_${to}.zip`,type:'application/zip'};}
