import {rateLimit} from './auth';
import {db,readState,saveState} from './server';
import {digest} from './passwords';
import type {Member,State} from './model';
export function normalizeCode(value:unknown){if(typeof value!=='string')throw new Error('Задайте код авторизации');const code=value.trim().toUpperCase();if(!/^[A-Z0-9]{8,32}$/.test(code)||/^(.)\1+$/.test(code)||/^(12345678|87654321|PASSWORD|QWERTY)/.test(code))throw new Error('Код: 8–32 латинские буквы и цифры, без пробелов и простых последовательностей');return code;}
// Codes never enter state snapshots, audit records or persistent dialog sessions.
export async function prepareInvite(s:State,actor:Member,target:string,isEmployee:boolean,value:unknown,old:number){const code=normalizeCode(value),key='sha256:'+digest(code);if(await db().prepare('SELECT code FROM invitations WHERE code=?').bind(key).first())throw new Error('Этот код уже использовался. Задайте другой.');let m:Member|undefined;
if(isEmployee){const e=s.employees.find(x=>x.id===target&&x.active);if(!e||!(actor.role==='admin'||actor.role==='manager'&&actor.branches.includes(e.branch)))throw new Error('Нет доступа к сотруднику');m=s.members.find(x=>x.employeeId===e.id);if(!m){m={id:crypto.randomUUID(),name:e.name,email:'',role:'employee',branches:[e.branch],phone:e.phone,employeeId:e.id,active:true};s.members.push(m);}else if(!m.active){Object.assign(m,{name:e.name,branches:[e.branch],phone:e.phone,active:true});delete m.telegramId;}}
else {m=s.members.find(x=>x.id===target&&x.active&&x.role!=='employee');if(!m||!(actor.role==='admin'||actor.id===m.id))throw new Error('Нет доступа');}
if(!m.active)throw new Error('Доступ отключён');if(m.telegramId)throw new Error('Telegram уже привязан к этому пользователю');
s.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),actor:actor.name,action:'Код Telegram задан',branch:m.branches[0],entityId:m.employeeId||m.id,detail:m.name+' · одноразовый код, срок 24 часа'});
const effects=[db().prepare('UPDATE invitations SET used=1 WHERE member_id=? AND used=0 AND EXISTS(SELECT 1 FROM app_state WHERE id=1 AND version=?)').bind(m.id,old),db().prepare('INSERT INTO invitations(code,member_id,expires,used) SELECT ?,?,?,0 WHERE EXISTS(SELECT 1 FROM app_state WHERE id=1 AND version=?)').bind(key,m.id,Date.now()+86400000,old)];return {code,effects};}
export async function createInvite(actor:Member,target:string,isEmployee:boolean,value?:unknown){const s=await readState();const current=s.members.find(m=>m.id===actor.id&&m.active);if(!current)throw new Error('Доступ отключён');const {code,effects}=await prepareInvite(s,current,target,isEmployee,value??crypto.randomUUID().replaceAll('-',''),s.version);s.version++;await saveState(s,s.version-1,undefined,effects);return code;}
export async function redeem(value:string,telegramId:number){await rateLimit('tg:'+telegramId,8);await rateLimit('tg:global',200);const code='sha256:'+digest(normalizeCode(value));const invite=await db().prepare('SELECT * FROM invitations WHERE code=? AND used=0 AND expires>?').bind(code,Date.now()).first<{member_id:string}>();if(!invite)throw new Error('Код недействителен или истёк. Попросите новый у управляющего.');const s=await readState();const m=s.members.find(x=>x.id===invite.member_id&&x.active);if(!m||m.telegramId||s.members.some(x=>x.telegramId===telegramId))throw new Error('Аккаунт уже привязан или доступ отключён');if(m.role==='employee'&&!s.employees.some(e=>e.id===m.employeeId&&e.active))throw new Error('Сотрудник выведен из состава');const before=structuredClone(m);m.telegramId=telegramId;s.version++;s.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),actor:m.name,action:'Telegram привязан',branch:m.branches[0],entityId:m.employeeId||m.id,detail:m.name,changes:[{kind:'members',id:m.id,before,after:structuredClone(m)}]});await saveState(s,s.version-1,{code,at:Date.now()});return m;}
