import branchCatalog from './branches.json';
import instructions from './instructions.json';
export type Role='admin'|'manager'|'employee';
export type Member={id:string;name:string;email:string;role:Role;branches:string[];employeeId?:string;telegramId?:number;active:boolean;phone?:string;avatarVersion?:number};
export type Employee={id:string;name:string;branch:string;job:'hall'|'loader';active:boolean;created:string;phone?:string;historical?:boolean};
export type Shift={id:string;employee:string;branch:string;date:string;start:string;end:string;breakMinutes:number;tasks:string[];status:'planned'|'working'|'review'|'confirmed'|'cancelled';reportedHours?:number;actualHours?:number;report?:string;photos?:string[];quality?:string;reason?:string;confirmedBy?:string;confirmedAt?:string;remindedAt?:string;employeeName?:string;employeeJob?:Employee['job'];branchName?:string};
export type Audit={id:string;at:string;actor:string;action:string;branch?:string;detail:string;changes?:{kind:string;id:string;before?:unknown;after?:unknown}[];entityId?:string};
export type Branch={id:string;name:string;city?:string;hours?:{day:number;closed:boolean;open:string;close:string}[];hoursUpdatedAt?:string;hoursUpdatedBy?:string};
export type State={branches:Branch[];employees:Employee[];shifts:Shift[];members:Member[];audit:Audit[];settings:{reminderMinutes:number;timezone:string};version:number};
export const statusText={planned:'Назначена',working:'На смене',review:'На подтверждении',confirmed:'Подтверждена',cancelled:'Отменена'};
export const jobText={hall:'Сотрудник зала',loader:'Грузчик'};
export function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Yekaterinburg'}).format(new Date());}
export function dateAdd(date:string,days:number){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
export function planHours(s:Pick<Shift,'start'|'end'|'breakMinutes'>){let a=s.start.split(':').map(Number),b=s.end.split(':').map(Number);let m=b[0]*60+b[1]-a[0]*60-a[1];if(m<=0)m+=1440;return Math.round((m-s.breakMinutes)/60*100)/100;}
export function shiftEnd(s:Shift){return new Date(`${s.end<=s.start?dateAdd(s.date,1):s.date}T${s.end}:00+05:00`).getTime();}
export function emptyState():State{return {branches:structuredClone(branchCatalog),employees:[],shifts:[],members:[],audit:[],settings:{reminderMinutes:15,timezone:'Asia/Yekaterinburg'},version:0};}
export function demoState():State{const s=emptyState();const t=today();s.members=[{id:'demo-admin',name:'Администратор РРС',email:'admin@example.test',role:'admin',branches:[],active:true},{id:'demo-manager',name:'Управляющий магазина',email:'manager@example.test',role:'manager',branches:['b1','b2'],active:true}];const names=['Алексей Миронов','Дмитрий Соколов','Елена Волкова','Андрей Лебедев','Максим Орлов','Ирина Белова','Сергей Козлов','Анна Морозова','Павел Новиков','Ольга Макарова','Никита Фролов','Роман Егоров'];s.employees=names.map((name,i)=>({id:'e'+i,name,branch:'b'+(i%6+1),job:i%3===0?'loader':'hall',active:i!==11,created:dateAdd(t,-20)}));
for(let d=-13;d<=3;d++){s.employees.forEach((e,i)=>{if(!e.active||(i+d+14)%4===0)return;const date=dateAdd(t,d),status:Shift['status']=d<-1?'confirmed':d===-1?(i%3===0?'review':'confirmed'):d===0?(i%3===0?'review':i%3===1?'working':'planned'):'planned';s.shifts.push({id:'s'+d+'_'+i,employee:e.id,branch:e.branch,date,start:'09:00',end:d===0&&i%3===0?'12:00':'18:00',breakMinutes:d===0&&i%3===0?0:60,tasks:e.job==='hall'?['hall-dust','hall-repricing']:['loader-unload'],status,...(status==='confirmed'?{actualHours:i%4===0?7:8,reportedHours:i%4===0?7:8,report:'Работы выполнены, результат передан ответственному.',quality:'Всё в порядке',confirmedBy:'Администратор РРС',confirmedAt:date+'T15:00:00Z',reason:i%4===0?'Работы завершены раньше':undefined}:status==='review'?{reportedHours:d===0?3:8,report:'Задачи завершены. Прошу подтвердить часы.'}:{})});});}return s;}
export function scoped(s:State,m:Member):State{if(m.role==='admin')return s;const allowed=(b:string)=>m.branches.includes(b);const shifts=s.shifts.filter(x=>m.role==='employee'?x.employee===m.employeeId:allowed(x.branch));return {...s,branches:s.branches.filter(b=>allowed(b.id)),employees:s.employees.filter(e=>m.role==='employee'?e.id===m.employeeId:allowed(e.branch)||shifts.some(x=>x.employee===e.id)).map(e=>{if(m.role==='employee'||allowed(e.branch))return e;const past=shifts.filter(x=>x.employee===e.id).sort((a,b)=>b.date.localeCompare(a.date))[0];return {id:e.id,name:past.employeeName||e.name,branch:past.branch,job:past.employeeJob||e.job,active:false,created:'',historical:true};}),shifts,members:s.members.filter(x=>x.id===m.id),audit:m.role==='employee'?[]:s.audit.filter(x=>x.entityId===m.id||x.changes?.some(c=>c.kind==='members'&&c.id===m.id)||x.branch&&allowed(x.branch))};}
export type Action={type:string;[key:string]:any};
function need(ok:unknown,message:string):asserts ok {if(!ok)throw new Error(message);}
function str(x:unknown,max=500){need(typeof x==='string'&&x.trim().length>0&&x.length<=max,'Проверьте заполнение полей');return x.trim();}
export function applyAction(source:State,m:Member,a:Action,now=Date.now()):State{
const s=structuredClone(source);need(m.active,'Доступ отключён');const admin=m.role==='admin';const manage=(b:string)=>admin||(m.role==='manager'&&m.branches.includes(b));let branch:string|undefined,detail='';let title='';
const id=()=>crypto.randomUUID();
// Freeze the currently known labels on legacy shifts before changing a directory entry.
if(['employee','branch'].includes(a.type))for(const shift of s.shifts){const e=source.employees.find(e=>e.id===shift.employee);shift.employeeName??=e?.name;shift.employeeJob??=e?.job;shift.branchName??=source.branches.find(b=>b.id===shift.branch)?.name;}
if(a.type==='employee') {branch=str(a.branch);need(manage(branch)&&s.branches.some(b=>b.id===branch),'Нет доступа к филиалу');need(['hall','loader'].includes(a.job),'Выберите функционал');const name=str(a.name,150);let e=s.employees.find(e=>e.id===a.id);need(!a.id||e,'Сотрудник не найден');if(e){need(manage(e.branch),'Нет доступа');need(!s.shifts.some(x=>x.employee===e!.id&&['working','review'].includes(x.status))||e.branch===branch,'Сначала закройте текущие смены');Object.assign(e,{name,branch,job:a.job,phone:typeof a.phone==='string'?a.phone.trim().slice(0,40):e.phone});const linked=s.members.find(u=>u.employeeId===e!.id);if(linked)Object.assign(linked,{name,branches:[branch],phone:e.phone});}else {need(!s.employees.some(e=>e.name.toLowerCase()===name.toLowerCase()&&e.branch===branch&&e.active),'Сотрудник уже есть в этом филиале');s.employees.push({id:id(),name,branch,job:a.job,phone:typeof a.phone==='string'?a.phone.trim().slice(0,40):'',active:true,created:today()});}title='Сотрудник сохранён';detail=name;}
else if(a.type==='archive'){const e=s.employees.find(x=>x.id===a.id);need(e&&manage(e.branch),'Нет доступа к сотруднику');need(!s.shifts.some(x=>x.employee===e.id&&['planned','working','review'].includes(x.status)),'Сначала отмените или закройте незавершённые смены');e.active=!e.active;branch=e.branch;title=e.active?'Сотрудник возвращён':'Сотрудник выведен из состава';detail=e.name;}
else if(a.type==='shift'){const e=s.employees.find(x=>x.id===a.employee);branch=str(a.branch);need(e&&e.active&&manage(e.branch)&&manage(branch)&&s.branches.some(b=>b.id===branch),'Нет доступа к сотруднику или филиалу');need(/^\d{4}-\d{2}-\d{2}$/.test(a.date)&&!isNaN(Date.parse(a.date))&&new Date(a.date).toISOString().slice(0,10)===a.date,'Укажите дату');need(/^([01]\d|2[0-3]):[0-5]\d$/.test(a.start)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(a.end),'Укажите время');need(Number.isInteger(a.breakMinutes)&&a.breakMinutes>=0&&a.breakMinutes<=240,'Перерыв: от 0 до 240 минут');need(Array.isArray(a.tasks)&&a.tasks.length&&a.tasks.every((t:unknown)=>typeof t==='string'),'Выберите задачи');need(a.tasks.every((t:string)=>(instructions as any)[e.job].tasks.some((q:any)=>q.id===t)),'Выбраны задачи другого функционала');const x:Shift={id:id(),employee:e.id,employeeName:e.name,employeeJob:e.job,branchName:s.branches.find(b=>b.id===branch)!.name,branch,date:a.date,start:a.start,end:a.end,breakMinutes:a.breakMinutes,tasks:a.tasks,status:'planned'};need(planHours(x)>0&&planHours(x)<=16,'Продолжительность смены: от 0 до 16 часов');const start=Date.parse(`${x.date}T${x.start}:00+05:00`);need(!s.shifts.some(q=>q.employee===e.id&&q.status!=='cancelled'&&Date.parse(`${q.date}T${q.start}:00+05:00`)<shiftEnd(x)&&shiftEnd(q)>start),'У сотрудника уже есть смена в это время');s.shifts.push(x);title='Смена назначена';detail=`${e.name} · ${a.date} · ${a.start}–${a.end}`;}
else if(['cancel','confirm','report','start','reopen'].includes(a.type)){const x=s.shifts.find(x=>x.id===a.id);need(x,'Смена не найдена');branch=x.branch;const own=m.role==='employee'&&m.employeeId===x.employee&&s.employees.some(e=>e.id===x.employee&&e.active);need(a.type==='report'||a.type==='start'?own:manage(branch),'Нет доступа к смене');detail=`${s.employees.find(e=>e.id===x.employee)?.name} · ${x.date}`;
if(a.type==='cancel'){need(x.status==='planned','Можно снять только с назначенной смены');x.reason=str(a.reason);x.status='cancelled';title='Смена отменена';}
if(a.type==='start'){need(x.status==='planned','Смена уже начата или закрыта');need(x.date===today(),'Можно начать только сегодняшнюю смену');x.status='working';title='Сотрудник начал смену';}
if(a.type==='report'){need(['planned','working','review'].includes(x.status),'Смена уже закрыта');need(Date.parse(x.date+'T'+x.start+':00+05:00')<=now,'Смена ещё не началась');need(Number.isFinite(a.hours)&&a.hours>=0&&a.hours<=24,'Часы: от 0 до 24');x.reportedHours=a.hours;x.report=str(a.report,2000);need(!a.photos||(Array.isArray(a.photos)&&a.photos.length<=5&&a.photos.every((p:unknown)=>typeof p==='string'&&p.length<300)),'Не более 5 фото');x.photos=a.photos||x.photos||[];x.status='review';title='Отчёт сдан';}
if(a.type==='confirm'){need(['review','working','planned'].includes(x.status),'Смена уже закрыта');need(now>=shiftEnd(x)||x.status==='review','Подтверждение доступно после смены или отчёта сотрудника');need(Number.isFinite(a.hours)&&a.hours>=0&&a.hours<=24,'Часы: от 0 до 24');need(['Всё в порядке','Есть замечания','Не вышел'].includes(a.quality),'Оцените качество');need(a.quality!=='Не вышел'||a.hours===0,'При невыходе укажите 0 часов');if(a.hours!==planHours(x)||a.quality!=='Всё в порядке')str(a.reason);x.actualHours=a.hours;x.quality=a.quality;x.reason=a.reason||'';x.status='confirmed';x.confirmedBy=m.name;x.confirmedAt=new Date(now).toISOString();title='Часы подтверждены';detail+=` · ${a.hours} ч · ${a.reason||a.quality}`;}
if(a.type==='reopen'){need(admin&&x.status==='confirmed','Корректировать закрытый табель может администратор');x.reason=str(a.reason);delete x.actualHours;delete x.confirmedBy;delete x.confirmedAt;x.status='review';title='Смена возвращена на проверку';detail+=' · '+x.reason;}
}
else if(a.type==='member'){need(admin,'Только для администратора');need(['admin','manager'].includes(a.role),'Выберите роль');const email=str(a.email,200).toLowerCase();need(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Укажите email');if(a.role==='admin')a={...a,branches:[]};need(Array.isArray(a.branches)&&a.branches.every((b:string)=>s.branches.some(x=>x.id===b)),'Выберите филиалы');need(a.role==='admin'||a.branches.length,'Назначьте хотя бы один филиал');let target=s.members.find(x=>x.id===a.id||x.email===email);need(!target||target.role!=='employee','Этот аккаунт закреплён за сотрудником');need(!target||!s.members.some(x=>x.id!==target!.id&&x.email===email),'Email уже используется');need(!target||target.id!==m.id||a.role==='admin','Нельзя снять собственные права администратора');const fields={name:str(a.name,150),phone:typeof a.phone==='string'?a.phone.trim().slice(0,40):target?.phone||'',email,role:a.role,branches:a.branches,active:true};if(target)Object.assign(target,fields);else s.members.push({id:id(),...fields});title='Права сохранены';detail=email;}
else if(a.type==='disableMember'){need(admin&&a.id!==m.id,'Нельзя отключить собственный доступ');const u=s.members.find(x=>x.id===a.id);need(u,'Пользователь не найден');u.active=!u.active;title=u.active?'Доступ включён':'Доступ отключён';detail=u.name;}
else if(a.type==='branch'){need(admin,'Только для администратора');const name=str(a.name,150);need(!s.branches.some(b=>b.name.toLowerCase()===name.toLowerCase()&&b.id!==a.id),'Такой филиал уже существует');const b=s.branches.find(b=>b.id===a.id);const city=str(a.city||b?.city||name.split(' · ')[0],80);need(['Тюмень','Тобольск','Ирбит','Тавда','Туринск'].includes(city),'Выберите город присутствия РРС');if(b)Object.assign(b,{name,city});else s.branches.push({id:id(),name,city});title='Филиал сохранён';detail=name;}
else if(a.type==='branchHours'){const b=s.branches.find(b=>b.id===a.id);need(b&&manage(b.id),'Нет доступа к филиалу');need(Array.isArray(a.hours)&&a.hours.length===7,'Укажите график на семь дней');const days=new Set<number>();for(const h of a.hours){need(Number.isInteger(h.day)&&h.day>=0&&h.day<=6&&!days.has(h.day),'Проверьте дни недели');days.add(h.day);need(typeof h.closed==='boolean','Укажите рабочие и выходные дни');need(/^([01]\d|2[0-3]):[0-5]\d$/.test(h.open)&&/^([01]\d|2[0-3]):[0-5]\d$/.test(h.close),'Укажите время в формате ЧЧ:ММ');need(h.closed||h.open!==h.close,'Начало и конец работы должны различаться');}b.hours=a.hours.map((h:any)=>({day:h.day,closed:h.closed,open:h.open,close:h.close}));b.hoursUpdatedAt=new Date(now).toISOString();b.hoursUpdatedBy=m.name;branch=b.id;title='График филиала изменён';detail=b.name;}
else if(a.type==='settings'){need(admin,'Только для администратора');need(Number.isInteger(a.reminderMinutes)&&a.reminderMinutes>=0&&a.reminderMinutes<=180,'Задержка: от 0 до 180 минут');s.settings.reminderMinutes=a.reminderMinutes;title='Настройки сохранены';detail=`Напоминание через ${a.reminderMinutes} мин`;}else throw new Error('Неизвестная команда');
const changes:{kind:string;id:string;before?:unknown;after?:unknown}[]=[];for(const kind of ['employees','shifts','members','branches'] as const){for(const after of s[kind]){const before=(source[kind] as {id:string}[]).find(v=>v.id===after.id);if(JSON.stringify(before)!==JSON.stringify(after))changes.push({kind,id:after.id,before:before?structuredClone(before):undefined,after:structuredClone(after)});}}if(a.type==='settings')changes.push({kind:'settings',id:'settings',before:source.settings,after:s.settings});s.audit.unshift({changes,id:id(),at:new Date(now).toISOString(),actor:m.name,action:title,branch,detail});s.version++;return s;
}
