import {getSession} from './auth';
import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '../chatgpt-auth';
import {emptyState,scoped,applyAction,type State,type Member,type Action} from './model';
export const db=()=> (env as any).DB as D1Database;
const kinds=['employees','shifts','members','audit'] as const;
function metadata(s:State){return JSON.stringify({...s,employees:[],shifts:[],members:[],audit:[]});}
// One read statement gives a consistent snapshot; each record has its own row.
export async function readState():Promise<State>{const result=await db().prepare("SELECT '__meta' AS kind,body FROM app_state WHERE id=1 UNION ALL SELECT kind,body FROM records").all<{kind:string;body:string}>();const meta=result.results.find(r=>r.kind==='__meta');if(!meta)return emptyState();const s=JSON.parse(meta.body) as State;for(const k of kinds)(s as any)[k]=result.results.filter(r=>r.kind===k).map(r=>JSON.parse(r.body));s.audit.sort((a,b)=>b.at.localeCompare(a.at));return s;}
export async function saveState(s:State,old:number,extraGuard?:{code:string;at:number},sideEffects?:D1PreparedStatement[]){const before=await readState();if(before.version!==old)throw new Error('Данные изменились. Обновите экран и повторите действие.');const auditById=new Map(s.audit.map(x=>[x.id,x]));for(const oldAudit of before.audit){const next=auditById.get(oldAudit.id);if(!next||JSON.stringify(next)!==JSON.stringify(oldAudit))throw new Error('Историю нельзя удалять или изменять');}const stmts:D1PreparedStatement[]=[];const guard=extraGuard?' AND EXISTS(SELECT 1 FROM invitations WHERE code=? AND used=0 AND expires>?)':'';const params:unknown[]=extraGuard?[old,extraGuard.code,extraGuard.at]:[old];
for(const k of kinds){const previous=new Map((before[k] as {id:string}[]).map(v=>[v.id,JSON.stringify(v)]));for(const v of s[k] as {id:string}[]){const body=JSON.stringify(v);if(previous.get(v.id)!==body)stmts.push(db().prepare(`INSERT INTO records(key,kind,body) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM app_state WHERE id=1 AND version=?${guard}) ON CONFLICT(key) DO UPDATE SET body=excluded.body`).bind(k+':'+v.id,k,body,...params));previous.delete(v.id);}for(const id of previous.keys())stmts.push(db().prepare(`DELETE FROM records WHERE key=? AND EXISTS(SELECT 1 FROM app_state WHERE id=1 AND version=?${guard})`).bind(k+':'+id,...params));}
if(sideEffects)stmts.push(...sideEffects);stmts.push(db().prepare(`UPDATE app_state SET body=?,version=? WHERE id=1 AND version=?${guard}`).bind(metadata(s),s.version,...params));const updateIndex=stmts.length-1;if(extraGuard)stmts.push(db().prepare('UPDATE invitations SET used=1 WHERE code=? AND EXISTS(SELECT 1 FROM app_state WHERE id=1 AND version=? AND body=?)').bind(extraGuard.code,s.version,metadata(s)));const results=await db().batch(stmts);if(!results[updateIndex].meta.changes)throw new Error('Данные изменились или приглашение уже использовано. Обновите экран и повторите действие.');}
export async function bootstrapIdentity(){const user=await getChatGPTUser();if(!user)throw new Error('Войдите в аккаунт');let s=await readState();if(!s.members.length){if(user.email.toLowerCase()!=='maiklvas@gmail.com')throw new Error('Владелец ещё не настроил рабочую базу. Пока доступен демо-режим.');const m:Member={id:crypto.randomUUID(),name:user.displayName,email:user.email.toLowerCase(),role:'admin',branches:[],active:true};const boot=crypto.randomUUID();const meta=JSON.stringify({...s,bootstrap:boot});await db().batch([db().prepare('INSERT OR IGNORE INTO app_state(id,body,version) VALUES (1,?,0)').bind(meta),db().prepare('INSERT OR IGNORE INTO records(key,kind,body) SELECT ?,?,? WHERE EXISTS(SELECT 1 FROM app_state WHERE id=1 AND body=?)').bind('members:'+m.id,'members',JSON.stringify(m),meta)]);s=await readState();}const m=s.members.find(x=>x.email===user.email.toLowerCase()&&x.active);if(!m||m.role==='employee')throw new Error('Нет доступа. Сотрудник работает через Telegram, права УМ выдаёт администратор.');return {s,m};}
export async function identity(allowPasswordChange=false){const session=await getSession();if(!session)throw Object.assign(new Error('Сеанс истёк. Войдите снова.'),{status:401});if(session.credential.must_change&&!allowPasswordChange)throw Object.assign(new Error('Сначала смените временный PIN'),{status:403});return {s:session.state,m:session.member};}
export async function mutate(m:Member,a:Action){const s=await readState();const current=s.members.find(x=>x.id===m.id&&x.active);if(!current)throw new Error('Доступ отключён');const n=applyAction(s,current,a);let effects:D1PreparedStatement[]=[];if(a.type==='employee'&&(!a.id||a.registrationCode)){const e=n.employees.find(e=>a.id?e.id===a.id:!s.employees.some(o=>o.id===e.id))!;const {prepareInvite}=await import('./invitations');effects=(await prepareInvite(n,current,e.id,true,a.registrationCode,s.version)).effects;}await saveState(n,s.version,undefined,effects);if(a.type==='shift'){const created=n.shifts.find(x=>!s.shifts.some(old=>old.id===x.id));if(created){try{const {notifyShiftAssigned}=await import('./telegram');await notifyShiftAssigned(created.id);}catch{console.error('Telegram assignment notification failed');}}}return n;}
export function payload(s:State,m:Member){return {state:scoped(s,m),user:m,botReady:!!(env as any).TELEGRAM_BOT_TOKEN,botUsername:(env as any).TELEGRAM_BOT_USERNAME||null};}
export function sameOrigin(r:Request){const o=r.headers.get('origin');if(!o||o!==new URL(r.url).origin)throw new Error('Недопустимый источник запроса');}
