import {credentialFor} from './auth';
import {env} from 'cloudflare:workers';
import {db,readState,mutate,saveState} from './server';
import {createInvite,redeem} from './invitations';
import {scoped,today,planHours,shiftEnd,statusText,jobText,type Member,type Shift,type State} from './model';
import raw from './instructions.json';
const instructions=raw as any;
const configuration=()=>env as any;
type Button={text:string;callback_data:string};
const btn=(text:string,callback_data:string):Button=>({text,callback_data});
export async function telegram(method:string,body:any){const token=configuration().TELEGRAM_BOT_TOKEN;if(!token)throw new Error('Telegram не подключён');const response=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(15000),body:JSON.stringify(body)});const result=await response.json() as any;if(!result.ok)throw new Error('Telegram не принял сообщение. Проверьте подключение бота.');return result.result;}
async function say(chat:number,text:string,buttons:Button[][]=[]){return telegram('sendMessage',{chat_id:chat,text:text.slice(0,4000),...(buttons.length?{reply_markup:{inline_keyboard:buttons}}:{})});}
async function eventKey(shiftId:string,memberId:string,kind:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(shiftId+':'+memberId+':'+kind));return 'sent:'+Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,'0')).join('');}
async function session(id:number,body?:any){if(body!==undefined){await db().prepare('INSERT INTO bot_sessions(id,body) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body').bind(String(id),JSON.stringify({...body,expires:Date.now()+3600000})).run();return body;}const row=await db().prepare('SELECT body FROM bot_sessions WHERE id=?').bind(String(id)).first<{body:string}>();if(!row)return {};const s=JSON.parse(row.body);return s.expires>Date.now()?s:{};}
const bn=(s:State,id:string)=>s.branches.find(x=>x.id===id)?.name||'Филиал';
const en=(s:State,id:string)=>s.employees.find(x=>x.id===id)?.name||'Сотрудник';
function shiftText(s:State,x:Shift){return `${en(s,x.employee)}\n${bn(s,x.branch)}\n${x.date} · ${x.start}–${x.end} (Тюмень)\nПлан: ${planHours(x)} ч · Перерыв: ${x.breakMinutes} мин\n${statusText[x.status]}${x.report?'\n\nОтчёт: '+x.report:''}${x.reportedHours!==undefined?'\nЗаявлено: '+x.reportedHours+' ч':''}${x.actualHours!==undefined?'\nПодтверждено: '+x.actualHours+' ч':''}`;}
function taskNames(s:State,x:Shift){const job=x.employeeJob||s.employees.find(e=>e.id===x.employee)?.job;return ((instructions[job||'hall']?.tasks||[]) as any[]).filter(t=>x.tasks.includes(t.id)).map(t=>t.title);}
function assignmentText(s:State,x:Shift,employee:boolean){const e=s.employees.find(e=>e.id===x.employee);const tasks=taskNames(s,x);return `${employee?'Вам назначена смена':'Сотруднику назначена смена'}\n\n${en(s,x.employee)} · ${jobText[x.employeeJob||e?.job||'hall']}\n${bn(s,x.branch)}\n${x.date} · ${x.start}–${x.end}\n\nЗадачи:\n${tasks.map((t,i)=>`${i+1}. ${t}`).join('\n')||'Задачи не указаны'}`;}
async function card(chat:number,s:State,m:Member,x:Shift){const buttons:Button[][]=[];if(m.role==='employee'){if(x.status==='planned')buttons.push([btn('Начать смену','start:'+x.id)]);buttons.push([btn('Мои задачи','tasks:'+x.id)]);if(['planned','working','review'].includes(x.status))buttons.push([btn('Сдать отчёт','report:'+x.id)]);}else {if(['planned','working','review'].includes(x.status))buttons.push([btn('Подтвердить часы','review:'+x.id)]);if(x.status==='planned')buttons.push([btn('Снять со смены','cancel:'+x.id)]);}await say(chat,shiftText(s,x),buttons);if(m.role!=='employee')for(const photo of x.photos||[])await telegram('sendPhoto',{chat_id:chat,photo});}
async function menu(chat:number,m:Member){await session(chat,{});await say(chat,`Здравствуйте, ${m.name}.\n${m.role==='employee'?'Здесь ваши смены, задачи и отчёты.':'Управление сменами ваших филиалов.'}`,m.role==='employee'?[[btn('Мои смены','list')]]:[[btn('Смены сегодня','list'),btn('На подтверждении','pending')],[btn('Назначить смену','newshift')],[btn('Добавить сотрудника','addemployee')],[btn('Пригласить сотрудника','inviteemployee')]]);}
async function employeePicker(chat:number,s:State,prefix:string){const employees=s.employees.filter(x=>x.active&&!x.historical&&s.branches.some(b=>b.id===x.branch));if(!employees.length)return say(chat,'Сначала добавьте сотрудника.');for(let i=0;i<employees.length;i+=30)await say(chat,'Выберите сотрудника',employees.slice(i,i+30).map(e=>[btn(`${e.name} · ${bn(s,e.branch)}`,prefix+':'+e.id)]));}
async function branchPicker(chat:number,s:State,prefix:string){for(let i=0;i<s.branches.length;i+=30)await say(chat,'Выберите филиал',s.branches.slice(i,i+30).map(b=>[btn(b.name,prefix+':'+b.id)]));}
export async function handleUpdate(update:any){const message=update.message,callback=update.callback_query;const chat=message?.chat||callback?.message?.chat;const tg=message?.from?.id||callback?.from?.id;if(!chat||chat.type!=='private'||chat.id!==tg)return;if(callback)await telegram('answerCallbackQuery',{callback_query_id:callback.id});const text=String(message?.text||'').trim(),data=String(callback?.data||'');
try{
if(text.startsWith('/start ')){const m=await redeem(text.slice(7).trim(),tg);await say(tg,'Аккаунт привязан.');return menu(tg,m);}
const all=await readState();const m=all.members.find(x=>x.telegramId===tg&&x.active);if(!m){if(text&&!text.startsWith('/')){const linked=await redeem(text,tg);await say(tg,'Аккаунт привязан.');return menu(tg,linked);}return say(tg,'Введите код авторизации, который вам передал управляющий или администратор. Код действует 24 часа и используется один раз.');}if(m.role==='employee'&&!all.employees.some(e=>e.id===m.employeeId&&e.active))return say(tg,'Вы выведены из текущего состава. Обратитесь к управляющему.');const s=scoped(all,m);const employee=m.role==='employee';if(!employee){const c=await credentialFor(m.id);if(!c||c.must_change)return say(tg,'Сначала войдите на сайт и смените временный PIN. После этого вернитесь в бот.');}
if(text==='/start'||text==='/menu'||text==='/cancel'||data==='menu')return menu(tg,m);
if(data==='list'||data==='pending'){const list=s.shifts.filter(x=>data==='pending'?(x.status==='review'||(['planned','working'].includes(x.status)&&shiftEnd(x)<Date.now())):employee?x.status!=='cancelled'&&x.date>=today():x.date===today());if(!list.length)return say(tg,'Таких смен нет.',[[btn('Меню','menu')]]);for(const x of list.slice(0,30))await card(tg,s,m,x);if(list.length>30)await say(tg,'Показаны первые 30 смен. Остальные доступны управляющему на сайте.');return;}
const [command,id]=data.split(':');const x=id?s.shifts.find(x=>x.id===id):undefined;
if(['start','report','tasks','review','cancel','same','less','more','noshow'].includes(command)){if(!x)throw new Error('Нет доступа к смене');
if(command==='start'){await mutate(m,{type:'start',id});return say(tg,'Начало смены отмечено.',[[btn('Мои задачи','tasks:'+id)],[btn('Сдать отчёт','report:'+id)]]);}
if(command==='tasks'){if(!employee)throw new Error('Команда сотрудника');const e=s.employees.find(e=>e.id===x.employee)!;const tasks=instructions[e.job].tasks.filter((t:any)=>x.tasks.includes(t.id));for(const t of tasks){const content=`${t.title}\n\n${t.tools?.length?'Инструменты: '+t.tools.join(', ')+'. '+(t.toolsNote||'')+'\n\n':''}${t.steps?.map((a:string,i:number)=>`${i+1}. ${a.replace('через эту инструкцию','в этом боте')}`).join('\n\n')||''}\n${(t.rules||[]).join('\n')}\n${(t.specialCases||[]).join('\n')}\n${t.warning||''}\n${t.note||''}`;for(let i=0;i<content.length;i+=3900)await say(tg,content.slice(i,i+3900));}return;}
if(command==='report'){if(!employee)throw new Error('Отчёт сдаёт сотрудник');await session(tg,{step:'report-hours',id});return say(tg,'Сколько часов отработали? Введите число, например 8 или 7,5. Перерыв не включайте.');}
if(employee)throw new Error('Только для управляющего');
if(command==='review')return say(tg,`План: ${planHours(x)} ч. Отчёт: ${x.reportedHours??'нет'} ч.\nСколько часов подтвердить?`,[[btn('По плану','same:'+id)],[btn('Меньше','less:'+id),btn('Больше','more:'+id)],[btn('Не вышел','noshow:'+id)]]);
if(command==='cancel'){await session(tg,{step:'cancel-reason',id});return say(tg,'Укажите причину снятия со смены. Отмена операции: /cancel');}
if(command==='same'){await session(tg,{step:'quality',id,hours:planHours(x)});return say(tg,'Оцените качество работы',[[btn('Всё в порядке','quality:good')],[btn('Есть замечания','quality:bad')]]);}
if(command==='noshow'){await session(tg,{step:'confirm-reason',id,hours:0,quality:'Не вышел'});return say(tg,'Укажите причину или обстоятельства невыхода.');}
if(command==='less'||command==='more'){await session(tg,{step:'confirm-hours',id,direction:command});return say(tg,`Введите фактические часы (${command==='less'?'меньше':'больше'} ${planHours(x)}).`);}
}
if(employee){const st=await session(tg);if(st.step==='report-hours'&&text){const hours=Number(text.replace(',','.'));if(!Number.isFinite(hours)||hours<0||hours>24)throw new Error('Введите число от 0 до 24');await session(tg,{...st,step:'report-text',hours});return say(tg,'Напишите, что сделали и где. Укажите проблемы, если они были.');}
if(st.step==='report-text'&&text){if(text.length>2000)throw new Error('Отчёт должен быть короче 2000 символов');await session(tg,{...st,step:'report-photos',report:text,photos:[]});return say(tg,'Пришлите до 5 фото результата, по одному. Когда закончите — нажмите «Отправить отчёт».',[[btn('Отправить отчёт','finishreport')]]);}
if(st.step==='report-photos'&&message?.photo){if(st.photos.length>=5)throw new Error('Уже добавлено 5 фото');st.photos.push(message.photo.at(-1).file_id);await session(tg,st);return say(tg,`Фото добавлено: ${st.photos.length} из 5.`,[[btn('Отправить отчёт','finishreport')]]);}
if(data==='finishreport'&&st.step==='report-photos'){await mutate(m,{type:'report',id:st.id,hours:st.hours,report:st.report,photos:st.photos});await session(tg,{});return say(tg,'Отчёт сохранён. Управляющий подтвердит часы.',[[btn('Меню','menu')]]);}return say(tg,'Откройте свои смены или продолжите отчёт. Отмена: /cancel',[[btn('Мои смены','list')]]);}
// Manager workflows. Every mutation rechecks the current server-side grants.
const st=await session(tg);
if(data==='addemployee'){await session(tg,{step:'employee-name'});return say(tg,'Введите ФИО нового сотрудника.');}
if(st.step==='employee-name'&&text){if(text.length>150)throw new Error('ФИО слишком длинное');await session(tg,{...st,name:text,step:'employee-branch'});return branchPicker(tg,s,'empbranch');}
if(command==='empbranch'&&st.step==='employee-branch'){if(!s.branches.some(b=>b.id===id))throw new Error('Нет доступа к филиалу');await session(tg,{...st,branch:id,step:'employee-job'});return say(tg,'Выберите функционал',[[btn('Сотрудник зала','empjob:hall')],[btn('Грузчик','empjob:loader')]]);}
if(command==='empjob'&&st.step==='employee-job'){if(!['hall','loader'].includes(id))throw new Error('Выберите функционал');await session(tg,{...st,job:id,step:'employee-code'});return say(tg,'Задайте код входа сотрудника: 8–32 латинские буквы и цифры. Передайте его сотруднику лично. Срок — 24 часа.');}
if(st.step==='employee-code'&&text){await mutate(m,{type:'employee',name:st.name,branch:st.branch,job:st.job,registrationCode:text});await session(tg,{});return say(tg,'Сотрудник добавлен. Передайте ему заданный код. В боте нужно нажать /start и отправить код.',[[btn('Назначить смену','newshift')],[btn('Пригласить в бот','inviteemployee')]]);}
if(data==='inviteemployee')return employeePicker(tg,s,'invite');
if(command==='invite'){await session(tg,{step:'invite-code',employee:id});return say(tg,'Задайте новый одноразовый код: 8–32 латинские буквы и цифры.');}
if(st.step==='invite-code'&&text){await createInvite(m,st.employee,true,text);await session(tg,{});return say(tg,'Код сохранён на 24 часа. Передайте его сотруднику лично. В боте: /start, затем код.');}
if(data==='newshift'){await session(tg,{step:'shift-employee'});return employeePicker(tg,s,'employee');}
if(command==='employee'&&st.step==='shift-employee'){const e=s.employees.find(e=>e.id===id&&e.active);if(!e)throw new Error('Нет доступа к сотруднику');await session(tg,{step:'shift-branch',employee:id,job:e.job});return branchPicker(tg,s,'shiftbranch');}
if(command==='shiftbranch'&&st.step==='shift-branch'){if(!s.branches.some(b=>b.id===id))throw new Error('Нет доступа к филиалу');await session(tg,{...st,step:'shift-date',branch:id});return say(tg,'Введите дату смены: ГГГГ-ММ-ДД. Например '+today());}
if(st.step==='shift-date'&&text){if(!/^\d{4}-\d{2}-\d{2}$/.test(text))throw new Error('Нужен формат ГГГГ-ММ-ДД');await session(tg,{...st,date:text,step:'shift-time'});return say(tg,'Введите начало, конец и перерыв в минутах через пробел. Например: 09:00 18:00 60');}
if(st.step==='shift-time'&&text){const [start,end,br]=text.split(/\s+/);if(!/^\d\d:\d\d$/.test(start||'')||!/^\d\d:\d\d$/.test(end||'')||!/^\d+$/.test(br||''))throw new Error('Пример: 09:00 18:00 60');await session(tg,{...st,start,end,breakMinutes:Number(br),step:'shift-tasks'});return say(tg,'Введите номера задач через запятую:\n'+instructions[st.job].tasks.map((t:any,i:number)=>`${i+1}. ${t.title}`).join('\n'));}
if(st.step==='shift-tasks'&&text){const nums=text.split(',').map(x=>Number(x.trim())-1);if(!nums.length||nums.some(n=>!Number.isInteger(n)||!instructions[st.job].tasks[n]))throw new Error('Выберите номера из списка');const tasks=[...new Set(nums)].map(n=>instructions[st.job].tasks[n].id);await session(tg,{...st,tasks,step:'shift-submit'});return say(tg,`Назначить ${en(s,st.employee)}?\n${bn(s,st.branch)}\n${st.date} · ${st.start}–${st.end}\nПерерыв: ${st.breakMinutes} мин\n${tasks.map(id=>instructions[st.job].tasks.find((x:any)=>x.id===id).title).join('\n')}`,[[btn('Назначить','submitshift')],[btn('Отмена','menu')]]);}
if(data==='submitshift'&&st.step==='shift-submit'){await mutate(m,{type:'shift',employee:st.employee,branch:st.branch,date:st.date,start:st.start,end:st.end,breakMinutes:st.breakMinutes,tasks:st.tasks});await session(tg,{});return say(tg,'Смена назначена.',[[btn('Меню','menu')]]);}
if(st.step==='confirm-hours'&&text){const x=s.shifts.find(x=>x.id===st.id);if(!x)throw new Error('Нет доступа');const hours=Number(text.replace(',','.'));if(!Number.isFinite(hours)||hours<0||hours>24||(st.direction==='less'?hours>=planHours(x):hours<=planHours(x)))throw new Error('Часы не соответствуют выбранному отклонению');await session(tg,{...st,hours,step:'quality'});return say(tg,'Как выполнены работы?',[[btn('Всё в порядке','quality:good')],[btn('Есть замечания','quality:bad')]]);}
if(command==='quality'&&st.step==='quality'){const x=s.shifts.find(x=>x.id===st.id);if(!x)throw new Error('Нет доступа');if(!['good','bad'].includes(id))throw new Error('Выберите качество');const quality=id==='good'?'Всё в порядке':'Есть замечания';await session(tg,{...st,quality,step:'confirm-reason'});if(st.hours!==planHours(x)||id==='bad')return say(tg,'Укажите причину отклонения часов или замечания.');await session(tg,{...st,quality,reason:'',step:'confirm-submit'});return say(tg,`Подтвердить ${st.hours} ч? Качество: ${quality}.`,[[btn('Подтвердить','submitconfirm')],[btn('Отмена','menu')]]);}
if(st.step==='confirm-reason'&&text){await session(tg,{...st,reason:text,step:'confirm-submit'});return say(tg,`Подтвердить ${st.hours} ч?\n${st.quality}\n${text}`,[[btn('Подтвердить','submitconfirm')],[btn('Отмена','menu')]]);}
if(data==='submitconfirm'&&st.step==='confirm-submit'){await mutate(m,{type:'confirm',id:st.id,hours:st.hours,quality:st.quality,reason:st.reason});await session(tg,{});return say(tg,'Часы подтверждены и включены в табель.',[[btn('На подтверждении','pending')],[btn('Меню','menu')]]);}
if(st.step==='cancel-reason'&&text){await session(tg,{...st,reason:text,step:'cancel-submit'});return say(tg,`Снять со смены? Причина: ${text}`,[[btn('Да, снять','submitcancel')],[btn('Отмена','menu')]]);}
if(data==='submitcancel'&&st.step==='cancel-submit'){await mutate(m,{type:'cancel',id:st.id,reason:st.reason});await session(tg,{});return say(tg,'Смена отменена. История сохранена.',[[btn('Меню','menu')]]);}
return say(tg,'Выберите команду в меню. Чтобы отменить текущий ввод: /cancel',[[btn('Меню','menu')]]);
}catch(e){await say(tg,(e as Error).message+'\nОтменить текущую операцию: /cancel');}
}
export async function deliverNotifications(){if(!configuration().TELEGRAM_BOT_TOKEN)return {sent:0,configured:false};let s=await readState();let count=0;const now=Date.now();
// Stable per-recipient event keys prevent repeat reminders after refresh or scheduler retry.
for(const x of s.shifts){if(count>=25)break;const employee=s.members.find(m=>m.active&&m.employeeId===x.employee&&m.telegramId);const recipients:{m:Member;kind:string;text:string}[]=[];
if(employee){if(x.status==='planned'&&x.date>=today())recipients.push({m:employee,kind:'assigned',text:'Вам назначена смена'});if(x.status==='confirmed'&&x.confirmedAt&&Date.parse(x.confirmedAt)>now-86400000)recipients.push({m:employee,kind:'confirmed-'+x.confirmedAt,text:'Управляющий подтвердил часы'});if(x.status==='cancelled')recipients.push({m:employee,kind:'cancelled',text:'Ваша смена отменена'});}
if(x.status==='review'||(['planned','working'].includes(x.status)&&now>=shiftEnd(x)+s.settings.reminderMinutes*60000)){for(const m of s.members.filter(m=>m.active&&m.telegramId&&(m.role==='admin'||m.role==='manager'&&m.branches.includes(x.branch))))recipients.push({m,kind:'review-'+(x.report||'overdue'),text:'Подтвердите отработанные часы'});}
for(const r of recipients){if(count>=25)break;const key=await eventKey(x.id,r.m.id,r.kind);const seen=await db().prepare('SELECT id FROM bot_sessions WHERE id=?').bind(key).first();if(seen)continue;
await say(r.m.telegramId!,r.text);await card(r.m.telegramId!,s,r.m,x);await db().prepare('INSERT OR IGNORE INTO bot_sessions(id,body) VALUES(?,?)').bind(key,JSON.stringify({at:now})).run();count++;}}
return {sent:count,configured:true};}

export async function notifyShiftAssigned(shiftId:string){if(!configuration().TELEGRAM_BOT_TOKEN)return {sent:0,configured:false};const s=await readState();const x=s.shifts.find(x=>x.id===shiftId);if(!x)return {sent:0,configured:true};const recipients:{m:Member;employee:boolean}[]=[];const employee=s.members.find(m=>m.active&&m.employeeId===x.employee&&m.telegramId);if(employee)recipients.push({m:employee,employee:true});for(const m of s.members.filter(m=>m.active&&m.telegramId&&(m.role==='admin'||m.role==='manager'&&m.branches.includes(x.branch))))recipients.push({m,employee:false});let sent=0;for(const r of recipients){const key=await eventKey(x.id,r.m.id,'assigned');const seen=await db().prepare('SELECT id FROM bot_sessions WHERE id=?').bind(key).first();if(seen)continue;const buttons=r.employee?[[btn('Посмотреть задачи','tasks:'+x.id)],[btn('Мои смены','list')]]:[[btn('Смены сегодня','list')],[btn('Меню','menu')]];await say(r.m.telegramId!,assignmentText(s,x,r.employee),buttons);await db().prepare('INSERT OR IGNORE INTO bot_sessions(id,body) VALUES(?,?)').bind(key,JSON.stringify({at:Date.now()})).run();sent++;}return {sent,configured:true};}
