import {credentialFor} from './auth';
import {env} from 'cloudflare:workers';
import {db,readState,mutate,saveState} from './server';
import {createInvite,redeem} from './invitations';
import {scoped,canManageBranch,today,dateAdd,planHours,shiftEnd,statusText,jobText,type Member,type Shift,type State} from './model';
import raw from './instructions.json';
const instructions=raw as any;
const configuration=()=>env as any;
type ButtonStyle='primary'|'success'|'danger';
type Button={text:string;callback_data:string;style?:ButtonStyle};
const btn=(text:string,callback_data:string,style?:ButtonStyle):Button=>({text,callback_data,...(style?{style}:{})});
export async function telegram(method:string,body:any){const token=configuration().TELEGRAM_BOT_TOKEN;if(!token)throw new Error('Telegram не подключён');for(let attempt=0;attempt<2;attempt++){let response:Response;try{response=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(15000),body:JSON.stringify(body)});}catch(e){if(attempt===0){await new Promise(r=>setTimeout(r,500));continue;}throw e;}const result=await response.json() as any;if(result.ok)return result.result;const retryAfter=Number(result.parameters?.retry_after||0),retryable=result.error_code===429||Number(result.error_code)>=500;if(attempt===0&&retryable&&retryAfter<=5){await new Promise(r=>setTimeout(r,Math.max(500,retryAfter*1000)));continue;}throw Object.assign(new Error(result.description||'Telegram не принял сообщение. Проверьте подключение бота.'),{telegramCode:result.error_code});}throw new Error('Telegram не принял сообщение.');}
export function telegramImageType(filePath:string,contentType:string|null){const declared=(contentType||'').split(';')[0].trim().toLowerCase();if(declared.startsWith('image/'))return declared;const ext=filePath.toLowerCase().match(/\.([a-z0-9]+)$/)?.[1]||'';const inferred:{[key:string]:string}={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',gif:'image/gif'};if(inferred[ext])return inferred[ext];if(declared==='application/octet-stream')return 'image/jpeg';return '';}
export async function telegramFile(fileId:string){const token=configuration().TELEGRAM_BOT_TOKEN;if(!token)throw Object.assign(new Error('Telegram не подключён'),{status:503});let file:any;try{file=await telegram('getFile',{file_id:fileId});}catch(e){throw Object.assign(new Error('Не удалось получить данные фото из Telegram'),{status:502,cause:e});}if(!file?.file_path||!/^[A-Za-z0-9_./-]+$/.test(file.file_path))throw Object.assign(new Error('Файл Telegram недоступен'),{status:502});let response:Response;try{response=await fetch(`https://api.telegram.org/file/bot${token}/${file.file_path}`,{signal:AbortSignal.timeout(15000)});}catch(e){throw Object.assign(new Error('Не удалось скачать фото из Telegram'),{status:502,cause:e});}if(!response.ok)throw Object.assign(new Error('Telegram не отдал фото'),{status:502});const type=telegramImageType(file.file_path,response.headers.get('content-type'));if(!type)throw Object.assign(new Error('Неподдерживаемый формат фото'),{status:415});return new Response(response.body,{headers:{'Content-Type':type,'Cache-Control':'private, no-store'}});}
async function say(chat:number,text:string,buttons:Button[][]=[]){return telegram('sendMessage',{chat_id:chat,text:text.slice(0,4000),...(buttons.length?{reply_markup:{inline_keyboard:buttons}}:{})});}
async function edit(chat:number,messageId:number|undefined,text:string,buttons:Button[][]=[]){if(!messageId)return say(chat,text,buttons);try{return await telegram('editMessageText',{chat_id:chat,message_id:messageId,text:text.slice(0,4000),reply_markup:{inline_keyboard:buttons}});}catch(e){if((e as Error).message.toLowerCase().includes('message is not modified'))return;throw e;}}
async function eventKey(shiftId:string,memberId:string,kind:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(shiftId+':'+memberId+':'+kind));return 'sent:'+Array.from(new Uint8Array(digest)).map(v=>v.toString(16).padStart(2,'0')).join('');}
async function session(id:number,body?:any){if(body!==undefined){await db().prepare('INSERT INTO bot_sessions(id,body) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body').bind(String(id),JSON.stringify({...body,expires:Date.now()+3600000})).run();return body;}const row=await db().prepare('SELECT body FROM bot_sessions WHERE id=?').bind(String(id)).first<{body:string}>();if(!row)return {};const s=JSON.parse(row.body);return s.expires>Date.now()?s:{};}
const bn=(s:State,id:string)=>s.branches.find(x=>x.id===id)?.name||'Филиал';
const en=(s:State,id:string)=>s.employees.find(x=>x.id===id)?.name||'Сотрудник';
export function parseShiftDate(value:string){const input=value.trim();let iso=input;const ru=input.match(/^(\d{1,2})[./](\d{1,2})[./](\d{4})$/);if(ru)iso=`${ru[3]}-${ru[2].padStart(2,'0')}-${ru[1].padStart(2,'0')}`;if(!/^\d{4}-\d{2}-\d{2}$/.test(iso))return null;const d=new Date(iso+'T12:00:00Z');return !Number.isNaN(d.getTime())&&d.toISOString().slice(0,10)===iso?iso:null;}
export function parseTaskSelection(value:string,count:number){const input=value.trim().toLowerCase();if(input==='все'||input==='all')return Array.from({length:count},(_,i)=>i);const parts=input.split(/[\s,;]+/).filter(Boolean);if(!parts.length)throw new Error('Выберите хотя бы одну задачу');const selected:number[]=[];for(const part of parts){const range=part.match(/^(\d+)-(\d+)$/);if(range){let a=Number(range[1]),b=Number(range[2]);if(a>b)[a,b]=[b,a];if(a<1||b>count)throw new Error('Выберите номера из списка');for(let n=a;n<=b;n++)selected.push(n-1);}else if(/^\d+$/.test(part)){const n=Number(part);if(n<1||n>count)throw new Error('Выберите номера из списка');selected.push(n-1);}else throw new Error('Можно указать номера, диапазон 1-7 или «все»');}return [...new Set(selected)];}
async function shiftTaskPicker(chat:number,st:any,messageId?:number){const tasks=instructions[st.job].tasks as any[],selected=new Set<string>(st.tasks||[]);const rows:Button[][]=tasks.map((t:any,i:number)=>[btn(`${selected.has(t.id)?'✅':'⬜'} ${i+1}. ${t.title}`,`picktask:${i}`,selected.has(t.id)?'success':undefined)]);rows.push([btn('✅ Выбрать все','pickall','primary'),btn('🧹 Очистить','picknone','danger')],[btn('Готово','pickdone','success')],[btn('Отмена','menu','danger')]);return edit(chat,messageId,`Выберите задачи для смены.\nВыбрано: ${selected.size} из ${tasks.length}\n\nМожно также отправить: 1 2 3, 1-7 или «все».`,rows);}
async function shiftTaskSubmit(chat:number,s:State,st:any,tasks:string[],messageId?:number){if(!tasks.length)throw new Error('Выберите хотя бы одну задачу');await session(chat,{...st,tasks,step:'shift-submit'});const catalog=instructions[st.job].tasks as any[];return edit(chat,messageId,`Назначить ${en(s,st.employee)}?\n${bn(s,st.branch)}\n${st.date} · ${st.start}–${st.end}\nПерерыв: ${st.breakMinutes} мин\n${tasks.map(taskId=>catalog.find((x:any)=>x.id===taskId)?.title||taskId).join('\n')}`,[[btn('Назначить','submitshift','success')],[btn('Назад к задачам','backtasks')],[btn('Отмена','menu','danger')]]);}
function shiftText(s:State,x:Shift){return `${en(s,x.employee)}\n${bn(s,x.branch)}\n${x.date} · ${x.start}–${x.end} (Тюмень)\nПлан: ${planHours(x)} ч · Перерыв: ${x.breakMinutes} мин\n${statusText[x.status]}${x.report?'\n\nОтчёт: '+x.report:''}${x.reportedHours!==undefined?'\nЗаявлено: '+x.reportedHours+' ч':''}${x.actualHours!==undefined?'\nПодтверждено: '+x.actualHours+' ч':''}`;}
function tasksFor(s:State,x:Shift){const job=x.employeeJob||s.employees.find(e=>e.id===x.employee)?.job;return ((instructions[job||'hall']?.tasks||[]) as any[]).filter(t=>x.tasks.includes(t.id));}
function taskNames(s:State,x:Shift){return tasksFor(s,x).map(t=>t.title);}
function assignmentText(s:State,x:Shift,employee:boolean){const e=s.employees.find(e=>e.id===x.employee);const tasks=taskNames(s,x);return `${employee?'Вам назначена смена':'Сотруднику назначена смена'}\n\n${en(s,x.employee)} · ${jobText[x.employeeJob||e?.job||'hall']}\n${bn(s,x.branch)}\n${x.date} · ${x.start}–${x.end}\n\nЗадачи:\n${tasks.map((t,i)=>`${i+1}. ${t}`).join('\n')||'Задачи не указаны'}`;}
async function taskPage(chat:number,s:State,x:Shift,index:number){const tasks=tasksFor(s,x);if(!tasks.length)return say(chat,'Для этой смены задачи не указаны.',[[btn('К смене','list')]]);const i=Math.max(0,Math.min(index,tasks.length-1)),t=tasks[i],report=x.taskReports?.find(r=>r.taskId===t.id);const details=`${i+1} из ${tasks.length} · ${t.title}\n\n${t.tools?.length?'Инструменты: '+t.tools.join(', ')+'. '+(t.toolsNote||'')+'\n\n':''}${t.steps?.map((a:string,n:number)=>`${n+1}. ${a.replace('через эту инструкцию','в этом боте')}`).join('\n\n')||''}\n${(t.rules||[]).join('\n')}${(t.specialCases||[]).length?'\n'+t.specialCases.join('\n'):''}${t.warning?'\n'+t.warning:''}${t.note?'\n'+t.note:''}${report?`\n\nОтчёт: ${report.status==='done'?'выполнено':'не выполнено'}${report.note?' · '+report.note:''} · фото: ${report.photos.length}`:'\n\nОтчёт ещё не заполнен.'}`;const nav:Button[]=[];if(i>0)nav.push(btn('← Предыдущая',`task:${x.id}:${i-1}`));if(i<tasks.length-1)nav.push(btn('Следующая →',`task:${x.id}:${i+1}`));const rows:Button[][]=[];if(nav.length)rows.push(nav);if(['planned','working','review'].includes(x.status))rows.push([btn(report?'Изменить отчёт':'Отчёт по задаче',`taskreport:${x.id}:${i}`)]);rows.push([btn('К сменам','list')]);return say(chat,details,rows);}
async function card(chat:number,s:State,m:Member,x:Shift){const buttons:Button[][]=[];if(m.role==='employee'){if(x.status==='planned')buttons.push([btn('Начать смену','start:'+x.id,'primary')]);buttons.push([btn('Мои задачи','tasks:'+x.id)]);if(['planned','working','review'].includes(x.status))buttons.push([btn('Сдать итоговый отчёт','report:'+x.id,'success')]);}else {if(['planned','working','review'].includes(x.status))buttons.push([btn('Подтвердить часы','review:'+x.id,'primary')]);if(x.status==='planned')buttons.push([btn('Снять со смены','cancel:'+x.id,'danger')]);}await say(chat,shiftText(s,x),buttons);if(m.role!=='employee'){for(const report of x.taskReports||[]){const title=tasksFor(s,x).find(t=>t.id===report.taskId)?.title||report.taskId;await say(chat,`Задача: ${title}\n${report.status==='done'?'Выполнено':'Не выполнено'}${report.note?'\nКомментарий: '+report.note:''}\nФото: ${report.photos.length}`);for(const photo of report.photos)await telegram('sendPhoto',{chat_id:chat,photo,caption:`${title} · ${report.status==='done'?'выполнено':'не выполнено'}`});}for(const photo of x.photos||[])await telegram('sendPhoto',{chat_id:chat,photo,caption:'Итоговый отчёт по смене'});}}
async function menu(chat:number,m:Member){await session(chat,{});await say(chat,`Здравствуйте, ${m.name}.\n${m.role==='employee'?'Здесь ваши смены, задачи и отчёты.':'Управление сменами ваших филиалов.'}`,m.role==='employee'?[[btn('Мои смены','list')]]:[[btn('Смены сегодня','list'),btn('На подтверждении','pending')],[btn('Назначить смену','newshift','primary')],[btn('Добавить сотрудника','addemployee','primary')],[btn('Пригласить сотрудника','inviteemployee')]]);}
async function employeePicker(chat:number,s:State,prefix:string){const employees=s.employees.filter(x=>x.active&&!x.historical&&s.branches.some(b=>b.id===x.branch));if(!employees.length)return say(chat,'Сначала добавьте сотрудника.');for(let i=0;i<employees.length;i+=30)await say(chat,'Выберите сотрудника',employees.slice(i,i+30).map(e=>[btn(`${e.name} · ${bn(s,e.branch)}`,prefix+':'+e.id)]));}
async function branchPicker(chat:number,s:State,prefix:string){for(let i=0;i<s.branches.length;i+=30)await say(chat,'Выберите филиал',s.branches.slice(i,i+30).map(b=>[btn(b.name,prefix+':'+b.id)]));}
export async function handleUpdate(update:any){const message=update.message,callback=update.callback_query;const chat=message?.chat||callback?.message?.chat;const tg=message?.from?.id||callback?.from?.id;if(!chat||chat.type!=='private'||chat.id!==tg)return;if(callback)await telegram('answerCallbackQuery',{callback_query_id:callback.id});const text=String(message?.text||'').trim(),data=String(callback?.data||''),callbackMessageId=callback?.message?.message_id;
try{
if(text.startsWith('/start ')){const m=await redeem(text.slice(7).trim(),tg);await say(tg,'Аккаунт привязан.');return menu(tg,m);}
const all=await readState();const m=all.members.find(x=>x.telegramId===tg&&x.active);if(!m){if(text&&!text.startsWith('/')){const linked=await redeem(text,tg);await say(tg,'Аккаунт привязан.');return menu(tg,linked);}return say(tg,'Введите код авторизации, который вам передал управляющий или администратор. Код действует 24 часа и используется один раз.');}if(m.role==='employee'&&!all.employees.some(e=>e.id===m.employeeId&&e.active))return say(tg,'Вы выведены из текущего состава. Обратитесь к управляющему.');const s=scoped(all,m);const employee=m.role==='employee';if(!employee){const c=await credentialFor(m.id);if(!c||c.must_change)return say(tg,'Сначала войдите на сайт и смените временный PIN. После этого вернитесь в бот.');}
if(text==='/start'||text==='/menu'||text==='/cancel'||data==='menu')return menu(tg,m);
if(data==='list'||data==='pending'){const list=s.shifts.filter(x=>data==='pending'?(x.status==='review'||(['planned','working'].includes(x.status)&&shiftEnd(x)<Date.now())):employee?x.status!=='cancelled'&&x.date>=today():x.date===today());if(!list.length)return say(tg,'Таких смен нет.',[[btn('Меню','menu')]]);for(const x of list.slice(0,30))await card(tg,s,m,x);if(list.length>30)await say(tg,'Показаны первые 30 смен. Остальные доступны управляющему на сайте.');return;}
const [command,id,arg]=data.split(':');const x=id?s.shifts.find(x=>x.id===id):undefined;
if(['start','report','tasks','task','taskreport','taskdone','taskskip','review','cancel','same','less','more','noshow'].includes(command)){if(!x)throw new Error('Нет доступа к смене');
if(command==='start'){await mutate(m,{type:'start',id});return say(tg,'Начало смены отмечено.',[[btn('Мои задачи','tasks:'+id)],[btn('Сдать отчёт','report:'+id)]]);}
if(command==='tasks'||command==='task'){if(!employee)throw new Error('Команда сотрудника');return taskPage(tg,s,x,command==='task'?Number(arg)||0:0);}
if(command==='taskreport'){if(!employee)throw new Error('Отчёт заполняет сотрудник');const index=Number(arg)||0,tasks=tasksFor(s,x),task=tasks[index];if(!task)throw new Error('Задача не найдена');return say(tg,`Как выполнена задача «${task.title}»?`,[[btn('Выполнено',`taskdone:${id}:${index}`,'success')],[btn('Не выполнено',`taskskip:${id}:${index}`,'danger')],[btn('Назад',`task:${id}:${index}`)]]);}
if(command==='taskdone'||command==='taskskip'){if(!employee)throw new Error('Отчёт заполняет сотрудник');const index=Number(arg)||0,tasks=tasksFor(s,x),task=tasks[index];if(!task)throw new Error('Задача не найдена');await session(tg,{step:'task-report',id,taskId:task.id,index,status:command==='taskdone'?'done':'not_done',note:'',photos:[]});return say(tg,`${command==='taskdone'?'Задача выполнена.':'Задача не выполнена.'}\nОтправьте комментарий или до 5 фото по одному.${command==='taskskip'?' Причину нужно указать обязательно.':''}`,[[btn('Сохранить отчёт','savetaskreport','success')],[btn('Отмена','menu','danger')]]);}
if(command==='report'){if(!employee)throw new Error('Отчёт сдаёт сотрудник');await session(tg,{step:'report-hours',id});return say(tg,'Сколько часов отработали? Введите число, например 8 или 7,5. Перерыв не включайте.');}
if(employee)throw new Error('Только для управляющего');
if(command==='review')return say(tg,`План: ${planHours(x)} ч. Отчёт: ${x.reportedHours??'нет'} ч.\nСколько часов подтвердить?`,[[btn('По плану','same:'+id,'success')],[btn('Меньше','less:'+id,'primary'),btn('Больше','more:'+id,'primary')],[btn('Не вышел','noshow:'+id,'danger')]]);
if(command==='cancel'){await session(tg,{step:'cancel-reason',id});return say(tg,'Укажите причину снятия со смены. Отмена операции: /cancel');}
if(command==='same'){await session(tg,{step:'quality',id,hours:planHours(x)});return say(tg,'Оцените качество работы',[[btn('Всё в порядке','quality:good','success')],[btn('Есть замечания','quality:bad','danger')]]);}
if(command==='noshow'){await session(tg,{step:'confirm-reason',id,hours:0,quality:'Не вышел'});return say(tg,'Укажите причину или обстоятельства невыхода.');}
if(command==='less'||command==='more'){await session(tg,{step:'confirm-hours',id,direction:command});return say(tg,`Введите фактические часы (${command==='less'?'меньше':'больше'} ${planHours(x)}).`);}
}
if(employee){const st=await session(tg);if(st.step==='task-report'&&message?.photo){if(st.photos.length>=5)throw new Error('Уже добавлено 5 фото');st.photos.push(message.photo.at(-1).file_id);await session(tg,st);return say(tg,`Фото добавлено: ${st.photos.length} из 5.`,[[btn('Сохранить отчёт','savetaskreport','success')],[btn('Отмена','menu','danger')]]);}
if(st.step==='task-report'&&text){if(text.length>2000)throw new Error('Комментарий должен быть короче 2000 символов');await session(tg,{...st,note:text});return say(tg,'Комментарий добавлен. Можно приложить фото или сохранить отчёт.',[[btn('Сохранить отчёт','savetaskreport','success')],[btn('Отмена','menu','danger')]]);}
if(data==='savetaskreport'&&st.step==='task-report'){const updated=await mutate(m,{type:'taskReport',id:st.id,taskId:st.taskId,status:st.status,note:st.note,photos:st.photos});await session(tg,{});const next=scoped(updated,m),shift=next.shifts.find(x=>x.id===st.id);if(!shift)throw new Error('Смена не найдена');await say(tg,'Отчёт по задаче сохранён. Он доступен управляющему.');return taskPage(tg,next,shift,st.index);}
if(st.step==='report-hours'&&text){const hours=Number(text.replace(',','.'));if(!Number.isFinite(hours)||hours<0||hours>24)throw new Error('Введите число от 0 до 24');await session(tg,{...st,step:'report-text',hours});return say(tg,'Напишите, что сделали и где. Укажите проблемы, если они были.');}
if(st.step==='report-text'&&text){if(text.length>2000)throw new Error('Отчёт должен быть короче 2000 символов');await session(tg,{...st,step:'report-photos',report:text,photos:[]});return say(tg,'Пришлите до 5 фото результата, по одному. Когда закончите — нажмите «Отправить отчёт».',[[btn('Отправить отчёт','finishreport','success')]]);}
if(st.step==='report-photos'&&message?.photo){if(st.photos.length>=5)throw new Error('Уже добавлено 5 фото');st.photos.push(message.photo.at(-1).file_id);await session(tg,st);return say(tg,`Фото добавлено: ${st.photos.length} из 5.`,[[btn('Отправить отчёт','finishreport','success')]]);}
if(data==='finishreport'&&st.step==='report-photos'){await mutate(m,{type:'report',id:st.id,hours:st.hours,report:st.report,photos:st.photos});await session(tg,{});return say(tg,'Отчёт сохранён. Управляющий подтвердит часы.',[[btn('Меню','menu')]]);}return say(tg,'Откройте свои смены или продолжите отчёт. Отмена: /cancel',[[btn('Мои смены','list')]]);}
// Manager workflows. Every mutation rechecks the current server-side grants.
const st=await session(tg);
if(data==='addemployee'){await session(tg,{step:'employee-name'});return say(tg,'Введите ФИО нового сотрудника.');}
if(st.step==='employee-name'&&text){if(text.length>150)throw new Error('ФИО слишком длинное');await session(tg,{...st,name:text,step:'employee-branch'});return branchPicker(tg,s,'empbranch');}
if(command==='empbranch'&&st.step==='employee-branch'){if(!s.branches.some(b=>b.id===id))throw new Error('Нет доступа к филиалу');await session(tg,{...st,branch:id,step:'employee-job'});return say(tg,'Выберите функционал',[[btn('Сотрудник зала','empjob:hall')],[btn('Грузчик','empjob:loader')]]);}
if(command==='empjob'&&st.step==='employee-job'){if(!['hall','loader'].includes(id))throw new Error('Выберите функционал');await session(tg,{...st,job:id,step:'employee-code'});return say(tg,'Задайте код входа сотрудника: 8–32 латинские буквы и цифры. Передайте его сотруднику лично. Срок — 24 часа.');}
if(st.step==='employee-code'&&text){await mutate(m,{type:'employee',name:st.name,branch:st.branch,job:st.job,registrationCode:text});await session(tg,{});return say(tg,'Сотрудник добавлен. Передайте ему заданный код. В боте нужно нажать /start и отправить код.',[[btn('Назначить смену','newshift','primary')],[btn('Пригласить в бот','inviteemployee')]]);}
if(data==='inviteemployee')return employeePicker(tg,s,'invite');
if(command==='invite'){await session(tg,{step:'invite-code',employee:id});return say(tg,'Задайте новый одноразовый код: 8–32 латинские буквы и цифры.');}
if(st.step==='invite-code'&&text){await createInvite(m,st.employee,true,text);await session(tg,{});return say(tg,'Код сохранён на 24 часа. Передайте его сотруднику лично. В боте: /start, затем код.');}
if(data==='newshift'){await session(tg,{step:'shift-employee'});return employeePicker(tg,s,'employee');}
if(command==='employee'&&st.step==='shift-employee'){const e=s.employees.find(e=>e.id===id&&e.active);if(!e)throw new Error('Нет доступа к сотруднику');await session(tg,{step:'shift-branch',employee:id,job:e.job});return branchPicker(tg,s,'shiftbranch');}
if(command==='shiftbranch'&&st.step==='shift-branch'){if(!s.branches.some(b=>b.id===id))throw new Error('Нет доступа к филиалу');await session(tg,{...st,step:'shift-date',branch:id});return say(tg,'Выберите дату или введите её сообщением: 10.09.2026 либо '+today()+'.',[[btn('Сегодня','shiftdate:today','primary'),btn('Завтра','shiftdate:tomorrow','primary')],[btn('Отмена','menu','danger')]]);}
if(command==='shiftdate'&&st.step==='shift-date'){const date=id==='today'?today():id==='tomorrow'?dateAdd(today(),1):null;if(!date)throw new Error('Не удалось выбрать дату');await session(tg,{...st,date,step:'shift-time'});return say(tg,'Введите начало, конец и перерыв в минутах через пробел. Например: 09:00 18:00 60');}
if(st.step==='shift-date'&&text){const date=parseShiftDate(text);if(!date)throw new Error('Введите дату как 10.09.2026 или ГГГГ-ММ-ДД');await session(tg,{...st,date,step:'shift-time'});return say(tg,'Введите начало, конец и перерыв в минутах через пробел. Например: 09:00 18:00 60');}
if(st.step==='shift-time'&&text){const [start,end,br]=text.split(/\s+/);if(!/^\d\d:\d\d$/.test(start||'')||!/^\d\d:\d\d$/.test(end||'')||!/^\d+$/.test(br||''))throw new Error('Пример: 09:00 18:00 60');const next={...st,start,end,breakMinutes:Number(br),tasks:[],step:'shift-tasks'};await session(tg,next);return shiftTaskPicker(tg,next);}
if(command==='picktask'&&st.step==='shift-tasks'){const catalog=instructions[st.job].tasks as any[],index=Number(id);if(!Number.isInteger(index)||!catalog[index])throw new Error('Задача не найдена');const selected=new Set<string>(st.tasks||[]);selected.has(catalog[index].id)?selected.delete(catalog[index].id):selected.add(catalog[index].id);const next={...st,tasks:[...selected]};await session(tg,next);return shiftTaskPicker(tg,next,callbackMessageId);}
if(data==='pickall'&&st.step==='shift-tasks'){const next={...st,tasks:(instructions[st.job].tasks as any[]).map((t:any)=>t.id)};await session(tg,next);return shiftTaskPicker(tg,next,callbackMessageId);}
if(data==='picknone'&&st.step==='shift-tasks'){const next={...st,tasks:[]};await session(tg,next);return shiftTaskPicker(tg,next,callbackMessageId);}
if(data==='pickdone'&&st.step==='shift-tasks')return shiftTaskSubmit(tg,s,st,st.tasks||[],callbackMessageId);
if(data==='backtasks'&&st.step==='shift-submit'){const next={...st,step:'shift-tasks'};await session(tg,next);return shiftTaskPicker(tg,next,callbackMessageId);}
if(st.step==='shift-tasks'&&text){const catalog=instructions[st.job].tasks as any[],nums=parseTaskSelection(text,catalog.length),tasks=nums.map(n=>catalog[n].id);return shiftTaskSubmit(tg,s,st,tasks);}
if(data==='submitshift'&&st.step==='shift-submit'){const known=new Set(s.shifts.map(x=>x.id));const updated=await mutate(m,{type:'shift',employee:st.employee,branch:st.branch,date:st.date,start:st.start,end:st.end,breakMinutes:st.breakMinutes,tasks:st.tasks});const created=updated.shifts.find(x=>!known.has(x.id));let delivery:any=null;if(created){try{delivery=await notifyShiftAssigned(created.id);}catch(e){console.error('Telegram assignment retry failed:',(e as Error).message);}}await session(tg,{});let message='Смена назначена.';if(!delivery?.configured)message+='\n⚠️ Уведомление сотруднику не отправлено: Telegram-бот не настроен.';else if(delivery.employee==='not_linked')message+='\n⚠️ Уведомление сотруднику не отправлено: сотрудник ещё не привязал Telegram.';else if(delivery.employee==='failed')message+='\n⚠️ Смена сохранена, но уведомление сотруднику доставить не удалось. Повторите попытку позже.';else message+='\n✅ Сотрудник получил уведомление в Telegram.';return say(tg,message,[[btn('Меню','menu')]]);}
if(st.step==='confirm-hours'&&text){const x=s.shifts.find(x=>x.id===st.id);if(!x)throw new Error('Нет доступа');const hours=Number(text.replace(',','.'));if(!Number.isFinite(hours)||hours<0||hours>24||(st.direction==='less'?hours>=planHours(x):hours<=planHours(x)))throw new Error('Часы не соответствуют выбранному отклонению');await session(tg,{...st,hours,step:'quality'});return say(tg,'Как выполнены работы?',[[btn('Всё в порядке','quality:good','success')],[btn('Есть замечания','quality:bad','danger')]]);}
if(command==='quality'&&st.step==='quality'){const x=s.shifts.find(x=>x.id===st.id);if(!x)throw new Error('Нет доступа');if(!['good','bad'].includes(id))throw new Error('Выберите качество');const quality=id==='good'?'Всё в порядке':'Есть замечания';await session(tg,{...st,quality,step:'confirm-reason'});if(st.hours!==planHours(x)||id==='bad')return say(tg,'Укажите причину отклонения часов или замечания.');await session(tg,{...st,quality,reason:'',step:'confirm-submit'});return say(tg,`Подтвердить ${st.hours} ч? Качество: ${quality}.`,[[btn('Подтвердить','submitconfirm','success')],[btn('Отмена','menu','danger')]]);}
if(st.step==='confirm-reason'&&text){await session(tg,{...st,reason:text,step:'confirm-submit'});return say(tg,`Подтвердить ${st.hours} ч?\n${st.quality}\n${text}`,[[btn('Подтвердить','submitconfirm','success')],[btn('Отмена','menu','danger')]]);}
if(data==='submitconfirm'&&st.step==='confirm-submit'){await mutate(m,{type:'confirm',id:st.id,hours:st.hours,quality:st.quality,reason:st.reason});await session(tg,{});return say(tg,'Часы подтверждены и включены в табель.',[[btn('На подтверждении','pending')],[btn('Меню','menu')]]);}
if(st.step==='cancel-reason'&&text){await session(tg,{...st,reason:text,step:'cancel-submit'});return say(tg,`Снять со смены? Причина: ${text}`,[[btn('Да, снять','submitcancel','danger')],[btn('Отмена','menu','danger')]]);}
if(data==='submitcancel'&&st.step==='cancel-submit'){await mutate(m,{type:'cancel',id:st.id,reason:st.reason});await session(tg,{});return say(tg,'Смена отменена. История сохранена.',[[btn('Меню','menu')]]);}
return say(tg,'Выберите команду в меню. Чтобы отменить текущий ввод: /cancel',[[btn('Меню','menu')]]);
}catch(e){await say(tg,(e as Error).message+'\nОтменить текущую операцию: /cancel');}
}
export async function deliverNotifications(){if(!configuration().TELEGRAM_BOT_TOKEN)return {sent:0,configured:false};let s=await readState();let count=0;const now=Date.now();
// Stable per-recipient event keys prevent repeat reminders after refresh or scheduler retry.
for(const x of s.shifts){if(count>=25)break;const employee=s.members.find(m=>m.active&&m.employeeId===x.employee&&m.telegramId);const recipients:{m:Member;kind:string;text:string}[]=[];
if(employee){if(x.status==='planned'&&x.date>=today())recipients.push({m:employee,kind:'assigned',text:'Вам назначена смена'});if(x.status==='confirmed'&&x.confirmedAt&&Date.parse(x.confirmedAt)>now-86400000)recipients.push({m:employee,kind:'confirmed-'+x.confirmedAt,text:'Управляющий подтвердил часы'});if(x.status==='cancelled')recipients.push({m:employee,kind:'cancelled',text:'Ваша смена отменена'});}
if(x.status==='review'||(['planned','working'].includes(x.status)&&now>=shiftEnd(x)+s.settings.reminderMinutes*60000)){for(const m of s.members.filter(m=>m.active&&m.telegramId&&canManageBranch(s,m,x.branch)))recipients.push({m,kind:'review-'+(x.report||'overdue'),text:'Подтвердите отработанные часы'});}
for(const r of recipients){if(count>=25)break;const key=await eventKey(x.id,r.m.id,r.kind);const seen=await db().prepare('SELECT id FROM bot_sessions WHERE id=?').bind(key).first();if(seen)continue;try{await say(r.m.telegramId!,r.text);await card(r.m.telegramId!,s,r.m,x);await db().prepare('INSERT OR IGNORE INTO bot_sessions(id,body) VALUES(?,?)').bind(key,JSON.stringify({at:now})).run();count++;}catch(e){console.error('Telegram scheduled notification failed:',r.m.id,(e as Error).message);}}}
return {sent:count,configured:true};}

type AssignmentEmployeeDelivery='sent'|'already_sent'|'not_linked'|'failed';
export async function notifyShiftAssigned(shiftId:string){if(!configuration().TELEGRAM_BOT_TOKEN)return {sent:0,configured:false,employee:'failed' as AssignmentEmployeeDelivery,managerSent:0,failed:0};const s=await readState();const x=s.shifts.find(x=>x.id===shiftId);if(!x)return {sent:0,configured:true,employee:'failed' as AssignmentEmployeeDelivery,managerSent:0,failed:1};const recipients:{m:Member;employee:boolean}[]=[];const employee=s.members.find(m=>m.active&&m.employeeId===x.employee&&m.telegramId);let employeeDelivery:AssignmentEmployeeDelivery=employee?'failed':'not_linked';if(employee)recipients.push({m:employee,employee:true});for(const m of s.members.filter(m=>m.active&&m.telegramId&&canManageBranch(s,m,x.branch)))recipients.push({m,employee:false});let sent=0,managerSent=0,failed=0;for(const r of recipients){const key=await eventKey(x.id,r.m.id,'assigned');const seen=await db().prepare('SELECT id FROM bot_sessions WHERE id=?').bind(key).first();if(seen){if(r.employee)employeeDelivery='already_sent';continue;}const buttons=r.employee?[[btn('Посмотреть задачи','tasks:'+x.id,'primary')],[btn('Мои смены','list')]]:[[btn('Смены сегодня','list','primary')],[btn('Меню','menu')]];try{await say(r.m.telegramId!,assignmentText(s,x,r.employee),buttons);await db().prepare('INSERT OR IGNORE INTO bot_sessions(id,body) VALUES(?,?)').bind(key,JSON.stringify({at:Date.now()})).run();sent++;if(r.employee)employeeDelivery='sent';else managerSent++;}catch(e){failed++;if(r.employee)employeeDelivery='failed';console.error('Telegram assignment notification failed:',r.m.id,(e as Error).message);}}return {sent,configured:true,employee:employeeDelivery,managerSent,failed};}
