import {identity,sameOrigin,saveState} from '../../lib/server';
import {env} from 'cloudflare:workers';
import {telegram} from '../../lib/telegram';
import {rateLimit} from '../../lib/auth';
const noStore={'Cache-Control':'no-store'};
export async function GET(r:Request){try{await identity();const configured=!!(env as any).TELEGRAM_BOT_TOKEN;if(!configured)return Response.json({configured:false,webhookConnected:false},{headers:noStore});const info=await telegram('getWebhookInfo',{});return Response.json({configured:true,webhookConnected:info.url===new URL('/api/telegram',r.url).href,pending:info.pending_update_count||0,lastError:!!info.last_error_message},{headers:noStore});}catch{return Response.json({error:'Не удалось проверить Telegram. Попробуйте позже.'},{status:503,headers:noStore});}}
export async function POST(r:Request){try{sameOrigin(r);const {s,m}=await identity();if(m.role!=='admin')return Response.json({error:'Подключение выполняет администратор'},{status:403});await rateLimit('telegram-connect:'+m.id,5);const secret=(env as any).TELEGRAM_WEBHOOK_SECRET;if(!secret||(env as any).TELEGRAM_BOT_TOKEN===undefined)throw new Error('Не заданы настройки бота');const url=new URL('/api/telegram',r.url);if(url.protocol!=='https:')throw new Error('Для подключения нужен опубликованный сайт');
// Anonymous request: never forward the user's cookies or platform credentials.
const probe=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(10000)});const marker=probe.ok?await probe.json().catch(()=>null):null;if(marker?.service!=='dns-telegram-webhook')return Response.json({error:'Сайт закрыт внешней проверкой доступа. Для Telegram нужен открытый адрес приёма сообщений. Изменение доступа согласуйте с владельцем; новый код не устранит эту блокировку.'},{status:409,headers:noStore});
await telegram('setWebhook',{url:url.href,secret_token:secret,allowed_updates:['message','callback_query'],drop_pending_updates:false});await telegram('setMyCommands',{commands:[{command:'start',description:'Войти по коду или открыть меню'},{command:'menu',description:'Главное меню'},{command:'cancel',description:'Отменить текущий ввод'}]});s.audit.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),actor:m.name,action:'Приём Telegram подключён',detail:'Адрес приёма проверен. Рабочие данные доступны только после авторизации.'});s.version++;await saveState(s,s.version-1);return Response.json({ok:true},{headers:noStore});}catch{return Response.json({error:'Не удалось подключить бота. Проверьте настройки и повторите проверку подключения.'},{status:503,headers:noStore});}}
