import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import {build} from 'esbuild';
const sql=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+f,'utf8'));
class Statement{constructor(q,p=[]){this.q=q;this.p=p;}bind(...p){return new Statement(this.q,p);}async first(){return sql.prepare(this.q).get(...this.p)||null;}async all(){return {results:sql.prepare(this.q).all(...this.p),meta:{changes:0}};}async run(){return {meta:{changes:Number(sql.prepare(this.q).run(...this.p).changes)}};}}
globalThis.__env={DB:{prepare:q=>new Statement(q),batch:async stmts=>{sql.exec('BEGIN');try{const a=[];for(const s of stmts)a.push(await s.run());sql.exec('COMMIT');return a;}catch(e){sql.exec('ROLLBACK');throw e;}}}};globalThis.__user={email:'maiklvas@gmail.com',displayName:'Владелец'};globalThis.__cookie=null;
const b=await build({stdin:{contents:"export * from './app/lib/auth';export * from './app/lib/server';export * from './app/lib/passwords';export {POST as saveUser} from './app/api/users/route';export {POST as authAction} from './app/api/auth/route';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false,plugins:[{name:'mock',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'mock'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'user',namespace:'mock'}));b.onResolve({filter:/^next\/headers$/},()=>({path:'headers',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='env'?'export const env=globalThis.__env;':a.path==='user'?'export async function getChatGPTUser(){return globalThis.__user;}':'export async function cookies(){return {get(){return globalThis.__cookie?{value:globalThis.__cookie}:undefined;}};}'}));}}]});const api=await import('data:text/javascript;base64,'+Buffer.from(b.outputFiles[0].text).toString('base64'));
const request=body=>new Request('https://app.test/api/auth',{method:'POST',headers:{origin:'https://app.test','Content-Type':'application/json'},body:JSON.stringify(body)});
let owner,manager;const ownerPass='483726';const temporary='284639';const newPass='573826';
test('password hashes differ by salt, verify correctly, policy enforced',()=>{const a=api.hashPassword(newPass),b=api.hashPassword(newPass);assert.notEqual(a,b);assert(api.verifyPassword(newPass,a));assert(!api.verifyPassword('incorrect',a));assert.throws(()=>api.hashPassword('short'));assert.doesNotThrow(()=>api.hashPassword('1111'));assert.doesNotThrow(()=>api.hashPassword('0123'));assert.throws(()=>api.hashPassword('123'));assert.throws(()=>api.hashPassword('12345a'));assert.throws(()=>api.hashPassword('1234567890123'));});
test('only verified owner may initialise without a branch; no SSO password bypass',async()=>{globalThis.__user={email:'outsider@example.test',displayName:'Чужой'};await assert.rejects(api.setupOwner(ownerPass,['b1']),/Владелец/);globalThis.__user={email:'maiklvas@gmail.com',displayName:'Владелец'};owner=await api.setupOwner(ownerPass);assert.deepEqual(owner.member.branches,[]);globalThis.__cookie=owner.raw;assert.equal((await api.identity()).m.role,'admin');globalThis.__cookie=null;await assert.rejects(api.identity(),/Войдите/);await assert.rejects(api.setupOwner('736284',['b1']),/уже задан/);});
test('admin creation requires role, branch, temporary password; hash stays outside member payload',async()=>{globalThis.__cookie=owner.raw;let r=await api.saveUser(request({type:'member',name:'Тестовый УМ',email:'manager@example.test',role:'manager',branches:[]}));assert.equal(r.status,400);r=await api.saveUser(request({type:'member',name:'Тестовый УМ',email:'manager@example.test',role:'manager',branches:['b1'],temporaryPassword:temporary}));assert.equal(r.status,200);const s=await api.readState();manager=s.members.find(m=>m.email==='manager@example.test');assert(!JSON.stringify(s).includes(temporary));assert(!JSON.stringify(s).includes('password_hash'));assert.equal((await api.credentialFor(manager.id)).must_change,1);});
test('temporary login cannot access workspace until password changed; session rotates',async()=>{const a=await api.login('manager@example.test',temporary,'test1');globalThis.__cookie=a.raw;assert.equal((await api.authStatus()).mustChange,true);await assert.rejects(api.identity(),/смените/);await assert.rejects(api.changePassword(temporary,temporary),/отличаться/);const n=await api.changePassword(temporary,newPass);assert.notEqual(n.raw,a.raw);assert.equal(await api.getSession(),null);globalThis.__cookie=n.raw;assert.equal((await api.identity()).m.id,manager.id);await assert.rejects(api.login('manager@example.test',temporary,'test1'),/Неверный/);});
test('profile whitelist prevents modifying roles or branches',async()=>{const r=await api.authAction(request({action:'profile',name:'Новое имя',phone:'+7 900',role:'admin',branches:['b2']}));assert.equal(r.status,200);const m=(await api.readState()).members.find(m=>m.id===manager.id);assert.equal(m.name,'Новое имя');assert.equal(m.role,'manager');assert.deepEqual(m.branches,['b1']);});
test('manager cannot create users; reset invalidates existing sessions',async()=>{let r=await api.saveUser(request({type:'member',name:'Hack',email:'hack@example.test',role:'admin',branches:['b1'],temporaryPassword:temporary}));assert.equal(r.status,400);const old=globalThis.__cookie;globalThis.__cookie=owner.raw;r=await api.saveUser(request({type:'member',id:manager.id,name:'Новое имя',email:manager.email,role:'manager',branches:['b1'],temporaryPassword:'963825'}));assert.equal(r.status,200);globalThis.__cookie=old;assert.equal(await api.getSession(),null);});
test('expired temporary passwords and invalid origin rejected',async()=>{sql.prepare('UPDATE credentials SET temp_expires=1 WHERE user_id=?').run(manager.id);await assert.rejects(api.login(manager.email,'963825','test1'),/истёк/);const r=await api.authAction(new Request('https://app.test/api/auth',{method:'POST',headers:{origin:'https://evil.test'},body:JSON.stringify({action:'logout'})}));assert.equal(r.status,400);});
test('rate limiter blocks repeated attempts; cookie carries security attributes',async()=>{for(let i=0;i<3;i++)await api.rateLimit('unit-test',3);await assert.rejects(api.rateLimit('unit-test',3),/Слишком много/);assert.match(api.cookie('x'),/HttpOnly; Secure; SameSite=Lax; Path=\//);});
test('admin accounts require no branches; managers still require assigned branches',async()=>{globalThis.__cookie=owner.raw;let r=await api.saveUser(request({type:'member',name:'Администратор сети',email:'network-admin@example.test',role:'admin',temporaryPassword:'639284'}));assert.equal(r.status,200);const user=(await api.readState()).members.find(m=>m.email==='network-admin@example.test');assert.deepEqual(user.branches,[]);r=await api.saveUser(request({type:'member',name:'УМ без филиала',email:'no-branch@example.test',role:'manager',branches:[],temporaryPassword:'926385'}));assert.equal(r.status,400);assert.match((await r.json()).error,/филиал/);});

test('owner recovery requires verified identity, revokes old sessions and ignores caller role fields',async()=>{globalThis.__cookie=null;globalThis.__user={email:'outsider@example.test'};let r=await api.authAction(request({action:'recoverOwner',password:'583926',email:'maiklvas@gmail.com',role:'admin'}));assert.equal(r.status,400);globalThis.__user=null;await assert.rejects(api.recoverOwner('583926'),/Подтвердите/);globalThis.__user={email:'maiklvas@gmail.com',displayName:'Владелец'};assert.equal((await api.authStatus()).canRecoverOwner,true);const n=await api.recoverOwner('583926');globalThis.__cookie=owner.raw;assert.equal(await api.getSession(),null);globalThis.__cookie=n.raw;assert.equal((await api.identity()).m.role,'admin');assert.deepEqual((await api.identity()).m.branches,[]);assert.equal((await api.credentialFor(n.member.id)).must_change,0);await assert.rejects(api.login('maiklvas@gmail.com',ownerPass,'test-recovery'),/Неверный/);assert.ok((await api.login('maiklvas@gmail.com','583926','test-recovery')).raw);assert.ok((await api.readState()).audit.some(a=>a.action==='PIN владельца восстановлен'));});
