'use client';
import {useEffect,useState} from 'react';
import {LockKeyhole,ShieldCheck,ArrowRight,LoaderCircle,Eye,EyeOff} from 'lucide-react';
import Workspace from './workspace';
import {authRequest} from './lib/auth-client';
export default function AccountGate(){const [status,setStatus]=useState<any>(null),[demo,setDemo]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[show,setShow]=useState(false),[recover,setRecover]=useState(false),[form,setForm]=useState({email:'',password:'',currentPassword:'',newPassword:'',repeat:''});
async function refresh(){try{const r=await fetch('/api/auth');const p=await r.json();if(!r.ok)throw new Error(p.error);setStatus(p);if(p.canSetupOwner)setForm(f=>({...f,email:p.ownerEmail||f.email}));}catch(e){setError((e as Error).message);setStatus({authenticated:false});}}
useEffect(()=>{setRecover(new URLSearchParams(window.location.search).get('recover')==='owner');refresh();},[]);
async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const forced=status?.authenticated&&status.mustChange;if((forced||recover)&&form.repeat!==(forced?form.newPassword:form.password))throw new Error('PIN-коды не совпадают');await authRequest(forced?{action:'changePassword',currentPassword:form.currentPassword,newPassword:form.newPassword}:recover?{action:'recoverOwner',password:form.password}:{action:'login',email:form.email,password:form.password});setForm({...form,password:'',currentPassword:'',newPassword:'',repeat:''});setRecover(false);window.history.replaceState(null,'',window.location.pathname);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
if(demo)return <Workspace initialDemo onExit={()=>setDemo(false)}/>;
if(status?.authenticated&&!status.mustChange)return <Workspace initialDemo={false} onExit={async()=>{await authRequest({action:'logout'});setStatus((previous:any)=>({authenticated:false,selfHosted:previous?.selfHosted}));}}/>;
const forced=status?.authenticated&&status.mustChange;
return <main className="auth-page"><div className="auth-brand"><b>DNS</b><span>РРС Тюмень · Внешний персонал</span></div><section className="auth-card"><div className="auth-icon"><LockKeyhole size={25}/></div><h1>{forced?'Задайте свой PIN':recover?'PIN владельца':'Вход в систему'}</h1><p>{forced?'Администратор выдал вам временный PIN. Прежде чем продолжить, замените его на личный.':recover?'Задайте новый PIN приложения. Старый PIN не нужен. Доступ ко всей сети сохранится.':'Введите email и цифровой PIN приложения.'}</p>{status===null?<div className="auth-loading"><LoaderCircle className="spin"/>Проверяем вход…</div>:<form className="form" onSubmit={submit}>
{!forced&&!recover&&<label>Email<input autoComplete="username" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="name@example.ru"/></label>}
{recover&&<div className="account-email">{status?.canRecoverOwner?'Подтверждён владелец: maiklvas@gmail.com':'Сначала подтвердите аккаунт maiklvas@gmail.com кнопкой ниже.'}</div>}{forced&&<><div className="account-email">{status.user.email}</div><label>Текущий временный PIN<input type="password" autoComplete="current-password" required value={form.currentPassword} onChange={e=>setForm({...form,currentPassword:e.target.value})}/></label></>}
<label>{forced||recover?'Новый личный PIN':'PIN'}<span className="password-input"><input type={show?'text':'password'} autoComplete={forced||recover?'new-password':'current-password'} required minLength={forced||recover?4:undefined} inputMode="numeric" pattern={forced||recover?'[0-9]{4,12}':undefined} maxLength={forced||recover?12:128} value={forced?form.newPassword:form.password} onChange={e=>setForm({...form,...(forced?{newPassword:e.target.value}:{password:e.target.value})})}/><button type="button" aria-label={show?'Скрыть PIN':'Показать PIN'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label>
{(forced||recover)&&<><label>Повторите новый PIN<input type="password" autoComplete="new-password" minLength={4} inputMode="numeric" pattern="[0-9]{4,12}" maxLength={12} required value={form.repeat} onChange={e=>setForm({...form,repeat:e.target.value})}/></label><small>От 4 до 12 цифр. Буквы и специальные символы не нужны.</small></>}

{error&&<p className="form-error" role="alert">{error}</p>}<button className="btn primary auth-submit" disabled={busy||(recover&&!status?.canRecoverOwner)}>{busy?<LoaderCircle size={18} className="spin"/>:<ArrowRight size={18}/>} {forced||recover?'Сохранить PIN и войти':'Войти'}</button>
{forced&&<button type="button" className="btn ghost" onClick={async()=>{await authRequest({action:'logout'});await refresh();}}>Выйти</button>}
</form>}
{!forced&&<><p className="auth-help">Нет PIN или забыли его? Администратор создаёт учётную запись и выдаёт новый временный PIN. Самостоятельной регистрации нет.</p>{!status?.selfHosted&&<a className="btn primary auth-submit" href="/signin-with-chatgpt?return_to=%2F%3Frecover%3Downer" target="_top">{recover?'Подтвердить владельца через ChatGPT':'Задать / восстановить PIN владельца'}</a>}{recover&&<button className="btn ghost" onClick={()=>{setRecover(false);setError('');}}>Вернуться ко входу</button>}<button className="btn ghost auth-demo" onClick={()=>setDemo(true)}>Посмотреть демо без рабочих данных<ArrowRight size={15}/></button></>}
</section><p className="auth-footer"><ShieldCheck size={16}/> Права и доступные филиалы назначает администратор</p></main>;
}
