'use client';
import TelegramConnection from './telegram-connection';
import {MessageCircle,Link,RefreshCw,TriangleAlert} from 'lucide-react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
export default function BotGuide({demo,admin=false}:{demo:boolean;admin?:boolean}){return <section className="panel bot-guide"><div className="panel-heading"><div><h2>Как войти и пользоваться ботом</h2><p>@HandyManRRS_bot</p></div></div><div className="bot-guide-body"><TelegramConnection admin={admin} demo={demo}/>
<h3>Авторизация по коду</h3><ol className="bot-how"><li>Войдите на сайт и смените временный PIN, если система попросит.</li><li>В «Личном кабинете» задайте код и нажмите «Сохранить код Telegram».</li><li>Откройте бота, нажмите /start и отправьте свой код. Можно воспользоваться ссылкой, которая подставит код автоматически.</li><li>После успешной привязки бот определяет вас по Telegram-аккаунту. Повторно вводить PIN не нужно.</li></ol><p className="profile-note">Для сотрудника код задаёт тот, кто создаёт его карточку. Он передаёт код сотруднику лично. Код действует 24 часа и используется один раз. Email или ФИО в сообщении боту не дают доступа.</p>
<Table><TableHeader><TableRow><TableHead>Команда</TableHead><TableHead>Что делает</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell><code>/start</code></TableCell><TableCell>Открывает бота. До авторизации просит код, после — показывает меню.</TableCell></TableRow><TableRow><TableCell><code>/menu</code></TableCell><TableCell>Возвращает главное меню с кнопками вашей роли.</TableCell></TableRow><TableRow><TableCell><code>/cancel</code></TableCell><TableCell>Отменяет текущий ввод. Уже сохранённые смены не удаляет.</TableCell></TableRow></TableBody></Table>
<div className="bot-role-grid"><div><h3>Управляющий и администратор</h3><p>Кнопки: «Смены сегодня», «На подтверждении», «Назначить смену», «Добавить сотрудника», «Пригласить сотрудника».</p><p>При назначении бот последовательно спрашивает сотрудника, филиал, дату, время, перерыв и задачи. В карточке смены УМ видит результат и фотографии каждой задачи, затем подтверждает часы и качество.</p></div><div><h3>Сотрудник</h3><p>«Мои смены» → «Мои задачи». Каждая задача открывается отдельно; кнопками «Предыдущая» и «Следующая» можно листать инструкции.</p><p>В «Отчёте по задаче» отметьте результат, добавьте комментарий или до 5 фото. После всех задач сдайте итоговый отчёт по смене. Часы попадут в табель только после подтверждения УМ.</p></div></div><p className="profile-note">Автоматические напоминания работают при включённом планировщике сервера. Состояние подключения видно выше.</p><a className="btn" href="https://t.me/HandyManRRS_bot" target="_blank" rel="noreferrer"><MessageCircle size={17}/>Открыть бота</a></div></section>;
}
