'use client';
import {useState,useEffect} from 'react';
import {CircleHelp,Clock3} from 'lucide-react';
import {Tooltip,TooltipTrigger,TooltipContent,TooltipProvider} from '@/components/ui/tooltip';
import type {Member,Branch} from './lib/model';
export function Help({text}:{text:string}){const [open,setOpen]=useState(false);return <TooltipProvider delayDuration={250}><Tooltip open={open} onOpenChange={setOpen}><TooltipTrigger asChild><button type="button" className="help-trigger" aria-label="Подсказка" onClick={()=>setOpen(!open)}><CircleHelp size={18}/></button></TooltipTrigger><TooltipContent className="help-content" sideOffset={8}>{text}</TooltipContent></Tooltip></TooltipProvider>;}
const tips:Record<string,string>={profile:'Сначала настройте личные данные. PIN нужен для сайта. Отдельный одноразовый код связывает Telegram с вашим профилем — повторно вводить его после привязки не нужно.',overview:'Сначала задайте часы магазина в «Настройках», затем добавьте сотрудника и назначьте смену. После отчёта подтвердите фактические часы.',people:'Добавьте ФИО, магазин и функционал. Код Telegram передайте сотруднику лично. Затем назначьте ему смену в разделе «Смены».',shifts:'Выберите сотрудника → филиал → дату и часы → задачи. После работы откройте смену, проверьте отчёт и подтвердите фактические часы.',timesheet:'В табель попадают только подтверждённые часы. Если часов нет, откройте «Смены» и проверьте, подтверждена ли работа.',analytics:'Выберите филиал и период, затем выгрузите Excel. Для каждого филиала создаётся отдельный файл, для каждого месяца — отдельная вкладка.',access:'Создайте пользователя, назначьте роль и филиалы УМ, затем передайте временный PIN. Администратору филиалы назначать не нужно.',settings:'УМ задаёт график только своих магазинов. Администратор видит все графики. Изменения сохраняются в истории.',bot:'Сначала проверьте подключение. Затем создайте код в личном кабинете, откройте бота и нажмите «Запустить». Дождитесь приветствия и меню.',history:'Здесь сохраняются автор, время и содержание изменений. Выберите период или найдите сотрудника по имени.'};
export function WorkflowHelp({view}:{view:string}){const tip=tips[view];return tip?<div className="workflow-help"><Help text={tip}/><span>{tip}</span></div>:null;}
export function LocalClock({member,branches}:{member:Member;branches:Branch[]}){const [now,setNow]=useState<Date|null>(null);useEffect(()=>{setNow(new Date());const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer);},[]);const cities=member.role==='admin'?['Тюмень']:[...new Set(branches.map(b=>b.city||b.name.split(' ')[0]))];return <div className="sidebar-note"><Clock3 size={16}/><div><strong>{cities.join(' / ')||'Город не назначен'}</strong><br/><time>{now?now.toLocaleTimeString('ru-RU',{timeZone:'Asia/Yekaterinburg'}):'—:—:—'}</time></div></div>;}
