import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {registerHooks} from 'node:module';import {runtimeEnv} from './runtime.mjs';
const origin=process.env.PUBLIC_ORIGIN;if(!origin||new URL(origin).protocol!=='https:')throw new Error('PUBLIC_ORIGIN must be an HTTPS origin');
globalThis.__dnsRuntimeEnv=runtimeEnv;registerHooks({resolve(s,c,next){if(s==='cloudflare:workers')return {url:'data:text/javascript,export const env=globalThis.__dnsRuntimeEnv',shortCircuit:true};return next(s,c);}});
const worker=(await import('../dist/server/index.js')).default;
const pending=new Set();const ctx={waitUntil(p){pending.add(p);p.catch(()=>console.error('Background task failed')).finally(()=>pending.delete(p));},passThroughOnException(){}};
const mime={'.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.jpeg':'image/jpeg','.woff2':'font/woff2','.ico':'image/x-icon'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,origin);if(url.origin!==origin){res.writeHead(400).end();return;}if(url.pathname==='/healthz'){res.writeHead(200,{'Content-Type':'application/json'}).end('{"ok":true}');return;}
const file=path.resolve('dist/client','.'+decodeURIComponent(url.pathname));if(file.startsWith(path.resolve('dist/client')+path.sep)&&fs.existsSync(file)&&fs.statSync(file).isFile()&&['GET','HEAD'].includes(req.method)){res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream','X-Content-Type-Options':'nosniff'});if(req.method==='HEAD')res.end();else fs.createReadStream(file).pipe(res);return;}
const headers=new Headers();for(const[k,v]of Object.entries(req.headers)){if(k.startsWith('oai-')||k==='host'||k==='cf-connecting-ip'||k.startsWith('x-forwarded-'))continue;if(v)headers.set(k,Array.isArray(v)?v.join(','):v);}headers.set('cf-connecting-ip',String(req.headers['x-dns-client-ip']||req.socket.remoteAddress||'local'));
let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>1100000){res.writeHead(413).end();return;}chunks.push(chunk);}const request=new Request(url,{method:req.method,headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})});const result=await worker.fetch(request,runtimeEnv,ctx);res.statusCode=result.status;for(const[k,v]of result.headers){if(k!=='set-cookie')res.setHeader(k,v);}if(result.headers.getSetCookie().length)res.setHeader('set-cookie',result.headers.getSetCookie());res.end(Buffer.from(await result.arrayBuffer()));}catch{console.error('Request failed');if(!res.headersSent)res.writeHead(500);res.end('Internal error');}});
server.listen(3000,'0.0.0.0');let running=false;
const timer=setInterval(async()=>{if(running)return;running=true;try{const r=await worker.fetch(new Request(origin+'/api/reminders',{method:'POST',headers:{Authorization:'Bearer '+runtimeEnv.REMINDER_SECRET}}),runtimeEnv,ctx);if(!r.ok)console.error('Reminder delivery failed');}catch{console.error('Reminder delivery failed');}finally{running=false;}},60000);
process.on('SIGTERM',()=>{clearInterval(timer);server.close(async()=>{await Promise.allSettled([...pending]);process.exit(0);});});
